### ISSUE TITLE
custom serializers not used for embedded associated records

### ISSUE THREAD

**Issue by jrr** [samselikoff/ember-cli-mirage#1002]
When serializing a model with an embedded associated model, the associated model is not subject to custom serialization.

In this [twiddle](https://ember-twiddle.com/cdf664cb5e00042fa0c47864e07c2662?openFiles=mirage.serializers.post.js%2C), see that the `post` serializer executes, but the `author` serializer does not.

From slack today:

> samselikoff [2:14 PM] 
@jrr I think it's a bug, you might want to overwrite `_hashForModel(model)` on the `author` serializer if you need to change that data
but I need to fix this. It should go through `#serialize`
i'm not sure. Might need to make `_hashForModel` public
when you serialize a resource you need to know if it's the main response (top-level). It's different if it's embedded

For anyone else that encounters this, here's an example of a workaround (using the same [pattern](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#serializeresponse-request) as overloading `serialize()`):

```
_hashForModel(/*model, removeForeignKeys, didSerialize={}*/) {
  let attrs = BaseSerializer.prototype._hashForModel.apply(this, arguments);

  // (mutate attrs here)

  return attrs;
}
```

When I find some time I'll take a stab at this issue.

**Comment by samselikoff** [comment]
I'm changing this from bug to feature request, since nested serializers are currently looked up correctly for included relationships – it's just that the `serialize()` function is only called for the top-level resource.

This is because `serialize()` is the entry point for building the entire payload, and there are different considerations when serializing a primary vs. included resource.

I need to understand what the original need was here, to know if we need to introduce new APIs for giving more control over serializing included resources. It might be as simple as making `hashForModel` public, but I don't want to do that until I understand the need further.

I'm going to close for now but please (anyone) feel free to ping here if you run into this issue/need and we can figure out a solution!

**Comment by samselikoff** [comment]
I also updated the documentation to clarify this point.

**Comment by velrest** [comment]
Im having the exact same problem. I have two models (A and B) with a custom serialize each. In the serializer i handle One to One relationships with have no inverse relationship since mirage does not serialize them.

If i include model B now on a GET to model A, i cant serialize the relationships since SerializerB#serialize is never called. Is there a workaround for this?

**Comment by samselikoff** [comment]
@velrest Could you open a new issue with a reproduction? This thread is almost a year old and it's easier to start from scratch on these sorts of things.
