### ISSUE TITLE
Release 0.3.0

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#1042]
- [x] Create 0.3 docs
- [x] Upgrade guide for 0.2 -> 0.3. Need to explain one-way keys.

**Comment by coladarci** [comment]
Hi @samselikoff - This release is amazing. I've just finished upgrading from an extremely complex `.2` -> `.3` setup and had some learnings that might help you and some other people.

# Mirage/config.js

## When defining routes, the model names are now plural:
```
  // 0.2
  this.post('/foo', ({ foo }, function () {
    return foo.create(); 
  })
```
```
  // 0.3
  this.post('/foo', ({ foos }, function () {
    return foos.create(); 
  })
```

## When accessing members of a collection, you have to starting asking for `models`:
```
// 0.2
const allFoos = foos.all();

allFoos.forEach(foo => ... );
```
```
// 0.3
const allFoos = foos.all().models;

allFoos.forEach(foo => ... );
```
**Note this also is the case for relationships:**

```
// 0.2
const myFoo = foos.all()[0];

myFoo.bars.forEach(bar => .... )
```
```
// 0.3
const myFoo = foos.all().models[0];

myFoo.bars.models.forEach(bar => .... )
```

# Factories

## UUID blew up for some reason:

```
// 0.2
export default Factory.extend({
  myUUID: faker.random.uuid,
});
```
> TypeError: self.number is not a function
>     at replacePlaceholders (http://localhost:4500/assets/vendor.js:121005:29)
>     at RegExp.[Symbol.replace] (<anonymous>)
>     at String.replace (native)
>     at Temp.Random.uuid (http://localhost:4500/assets/vendor.js:121009:31)
>     at http://localhost:4500/assets/vendor.js:131846:26
>     at Array.forEach (native)
>     at sortAttrs (http://localhost:4500/assets/vendor.js:131841:24)
>     at Subclass.Factory.build (http://localhost:4500/assets/vendor.js:131723:18)
>     at Server.build (http://localhost:4500/assets/vendor.js:136435:26)
>     at Server.create (http://localhost:4500/assets/vendor.js:136476:32)

```
// 0.3
export default Factory.extend({
  myUUID(i) {
    return i; // wasn't important for me to have this be an actual UUID so I could punt.
  })
});
```

# Scenarios

## When creating relationships, remove all `Ids`

```
// 0.2
const foo = server.create('foo');
const many = server.create('many');

const bar = server.create('bar', {
  fooId: foo.id,
  manyIds: [many.id]
});
```
```
// 0.3
const foo = server.create('foo');
const many = server.create('many');

const bar = server.create('bar', {
  foo: foo,
  manies: [many]
});
```
## New create helper doesn't run through factory, so wasn't helpful
In the following example, assume I have specified a `bar` factory that generates a bunch of good fixture data. The first `bar` I create below does what I would expect (in that it uses the factory), the second has all the un-specified fields left as null.
```
// 0.3
const foo = server.create('foo');

const withFactory = server.create('bar', {
  foo: foo,
});

const withoutFactory = foo.createBar({
  foo: foo,
});
```

## Serializers
There were a handful of models for which I hadn't created a serializer to tell it to `include` some relationships. They were heavily nested: 
`foo` hasMany `bars` who haveMany `biz`
I only had specified includes on the top level model, and it auto-included all relationships (which wasn't intentional, but I was relying on that happening, it turns out). 
The fix was to be explicit and define all the serializers. Cryptic bug, but made total sense. 

That's it! I'll keep adding if I come up w/ more, but I think this does it.. Great work - I'm about to get into the many-to-many world which was the only thing I couldn't model w/ my `0.2` stack because I didn't want to deal w/ the join table..

You're the best - thanks for all this hard work!

**Comment by coladarci** [comment]
So after writing the above, I've discovered that while my tests pass in the browser, running them w/ `ember test` results in the much dreaded
`Error: Assertion Failed: You have turned on testing mode, which disabled the run-loop's autorun. You will need to wrap any code with asynchronous side-effects in a run`.

After first they were failing because I believe you were using `Object.assign` and I didn't have 
```
    babel: {
      includePolyfill: true,
    },
```
in my `ember-cli-build`, but now that I've added this, I no longer get the `Object.assign` error but my first acceptance test hangs w/ that error. Is there any chance you have some ideas around what could potentially be happening? Perhaps an outdated dependent library?

**Comment by samselikoff** [comment]
Thanks for the writeup!

> 1. When defining routes, the model names are now plural

This shouldn't have changed from 0.2 to 0.3, can you verify?

> 2. When accessing members of a collection, you have to starting asking for models

This also has been true for a while in 0.2. The `.models` property is there to expose a "true" JS array (since arrays can't really be subclassed). We have some helper methods on the Collection object and I'm open to adding more

> 3. UUID blew up for some reason

Hmm, did the `faker` version change? Again nothing in 0.3 should have affected this..

> 4. Scenarios: When creating relationships, remove all Ids

Ids still work, look at https://ember-twiddle.com/5f61a0fda84b682db6ad0115a72f7b11

> 5. New create helper doesn't run through factory, so wasn't helpful

The model.createRelationship never used a factory, think of it as `store.createRecord` from Ember Data. `server.create` is how you use factories so if you want to create a related record I would do `server.create('foo', { bar })`. 

By the way in your example you do `foo.createBar({ foo: foo })` but this is unnecessary, `foo.createBar()` will create a `bar` that is related to `foo`.

> 6. Serializers

Hmm again this shouldn't have changed.. sure you weren't sending `?include=bars.biz` in your request?

> 7. PhantomJS

This was a pain point for others so we removed Object.assign. The node v4 support is unfortunately end-of-lifed so sorry you had to go through that, though you would have probably run into something else soon.

Let me know if any of this is confusing, happy to add some things to the upgrade guide if need be. And thanks again for this writing so others can benefit!

**Comment by samselikoff** [comment]
Closing this issue for now since 0.3 is released, but feel free to ask additional questions!

**Comment by blimmer** [comment]
The UUID issue is documented on the Faker side here:

https://github.com/Marak/faker.js/issues/368

It was not backported to the version of faker relied on (3.1.x). If anyone find this PR, you can work around that issue by changing:

```javascript
myUUID: faker.random.uuid
```

to

```javascript
myUUID: faker.random.uuid.bind(faker.random)
```
