### ISSUE TITLE
Lodash uniqBy going from 0.3.0-beta.5 to > 0.2.6

### ISSUE THREAD

**Issue by snewcomer** [samselikoff/ember-cli-mirage#1059]
Seems like going updating mirage from 0.3.0-beta.5 (lodash 0.0.9) to 0.2.6 or after, it says uniqBy is not a function.  I then installed the latest version of ember-lodash just to check and still doesn't work.  Having trouble producing with an ember-twiddle though.  Any quick thoughts?

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/serializers/json-api-serializer.js#L83

<img width="726" alt="screen shot 2017-03-28 at 12 32 22 pm" src="https://cloud.githubusercontent.com/assets/7374640/24423666/a311ccca-13b2-11e7-9674-87d5002b3842.png">

**Comment by snewcomer** [comment]
npm ls lodash gives me some info so guessing I will have to dig deeper here.  Will close for now.

**Comment by nmcclay** [comment]
I have encountered this issue as well... I think there is something odd going on with related to the version of lodash that is being resolved to being incorrect.  Oddly running this in twiddle didn't reproduce the issue as you mentioned.

**Comment by snewcomer** [comment]
@nmcclay for me it was another dependency installing an earlier version of lodash (and not using yarn yet, I don't have deterministic installs.  After you install, did you try `npm ls lodash`?

**Comment by ibroadfo** [comment]
So the issue here is with the way ember builds an app's dependencies into a single js file; if you have conflicting versions of a dep only one of them gets included, and which one gets selected isn't quite obvious.

Running `npm ls ember-lodash` or installing `ember-cli-dependency-lint` will show you which packages are depending on an old version; for me it was emberfire. I was able to fork and upgrade <https://github.com/firebase/emberfire/pull/495>.

**Comment by QuantumInformation** [comment]
Just run into this as well. Thanks @ibroadfo.

**Comment by iballack** [comment]
Any solution for this issue?

**Comment by ibroadfo** [comment]
@iballack the only solution is to upgrade the conflicting addons as I described above. There's no other way around this at present sadly.
