### ISSUE TITLE
Associations persisting between separate tests

### ISSUE THREAD

**Issue by Bushjumper** [samselikoff/ember-cli-mirage#1071]
Greetings :-)

I'm attempting to upgrade from 0.2.4 to 0.3.1.

We mostly use a set of fixtures to run all of our acceptance tests. I've updated both sides of our associations throughout the fixtures, as per the upgrade notes.

We have teams and people in our app. A team has many people and a person belongs to a team.

When I run a suite of tests where a person is created in a test, subsequent tests seem to fail because the new person id exists for the team.personIds association, but the new person record has been cleared due to loadFixtures between tests.

An example of the error is:

_**Error: Mirage: You're instantiating a team that has a personIds of 1,2,3,4,1,f7dd226e-c361-46f2-8d2a-92a55d8825f8, but some of those records don't exist in the database.**_

Individually, the tests always run ok. On occasion, the tests pass together.

It's as if the team.personIds association is not being reset between tests. Is that possible? Any ideas on where I can look to resolve it? Happy to dig into the source code, with a bit of direction.

Thanks,
Graeme

**Comment by BnitoBzh** [comment]
i have the same issue, i have just migrate all my tests from factories mode to fixtures mode ...
did you found a solution ??

i have searched the problem and when the 'utils/read-modules' script is executed on startMirage function, relationship Ids are already setted with the previous test's data instead of be resetted by fixture data ...

**Comment by samselikoff** [comment]
I apologize for not responding to this!

I believe there was some fixes in the last year that prevented route handlers from mutating upstream fixture files, so a more recent version of Mirage should address your issue here.

I'll go ahead and close this issue for now since it's quite old, but if you’re still having trouble, please ping me here or on slack @samselikoff and I will reopen + discuss.
