### ISSUE TITLE
Use within development of an addon

### ISSUE THREAD

**Issue by pzuraq** [samselikoff/ember-cli-mirage#108]
Is Mirage usable when developing an addon? We are developing a location service that makes API calls to google, testing it has been difficult because we are making ajax calls and we wanted to override those with mirage.

**Comment by samselikoff** [comment]
hmm. I actually don't know, I imagine the normal rules apply, and I think addons can rely on other addons? 

I would not that currently, mirage does not support other-origin requests - e.g. making a request directly to http://www.google.com from your ember app. This is because pretender doesn't support it right now. We will solve this one day, perhaps by using mockjax when other-origin requests are made. But it is lower in priority than the ORM stuff in the works right now.

**Comment by clekstro** [comment]
I don't want to clobber this issue, but I'm having problems with integrating this addon within a brand new ember addon.  If you generate a new ember addon and specify this addon as a dependency in `package.json`, en error is thrown when running `ember test`:

```bash
version: 0.2.5
Build failed.
Path or pattern "bower_components/FakeXMLHttpRequest/fake_xml_http_request.js" did not match any files
```

I tried adding this to the dependencies instead of to devDependencies, but just get a different error:

```bash
undefined is not a function
TypeError: undefined is not a function
    at Class.included (/Users/username/code/packages/addon-using-mirage/node_modules/ember-cli-mirage/index.js:14:17)
```

**Comment by samselikoff** [comment]
hm, what about running generator? `ember g ember-cli-mirage`?

**Comment by clekstro** [comment]
That seemed to do the trick. Thanks!

**Comment by samselikoff** [comment]
right now, https://github.com/ember-cli/ember-cli/issues/3718 is blocking this

**Comment by DmitriWolf** [comment]
Sam,
Thank you so much for your hard work on this project.
Is there a successful way to get Mirage to work in an Addon inside an Addon? 

I have tried `ember g ember-cli-mirage` and get the error `The 'ember-cli-mirage' blueprint does not support generating inside addons.`
Thanks

**Comment by samselikoff** [comment]
I'll have to look into this, I think it's because mirage tries to generate files into `/app`. I wonder if we can detect if it's being installed in an addon and install the files to (and read them from) `/addon`.

**Comment by Samsinite** [comment]
Does creating a blueprint called `ember-cli-mirage-addon` work? I noticed that ember-cli postfixes all of their addon generators with `-addon`. I'm wondering if ember-cli automatically looks for this already.

**Comment by Samsinite** [comment]
@DmitriWolf does adding the bower dependencies and installing the files in https://github.com/samselikoff/ember-cli-mirage/tree/master/blueprints/ember-cli-mirage/files into `tests/dummy` work?

**Comment by Samsinite** [comment]
I can confirm that installing the bower dependencies listed in https://github.com/samselikoff/ember-cli-mirage/blob/master/blueprints/ember-cli-mirage/index.js and installing the default files inside of https://github.com/samselikoff/ember-cli-mirage/tree/master/blueprints/ember-cli-mirage/files to `tests/dummy` based off of their appropriate path works like a charm inside of an addon for testing.

**Comment by samselikoff** [comment]
Don't have time to look at this just now, if someone can figure out how others are doing this + share here that'd be much appreciated!

**Comment by Samsinite** [comment]
@samselikoff Now that I have time, a PR is submitted based off of suggestion from earlier.
