### ISSUE TITLE
Are factories JSON API compliant?

### ISSUE THREAD

**Issue by eccegordo** [samselikoff/ember-cli-mirage#109]
I believe JSON API is suppose to hit 1.0 later in May.

Take canonical contacts example

```
[
  {
    "admin": false,
    "age": 20,
    "email": "person0@test.com",
    "id": 1,
    "name": "Pete"
  }
]
```

I believe per JSON API specs it needs to be represented this way

A single resource instance
```
{
  "data": {
	    "admin": false,
	    "age": 20,
	    "email": "person0@test.com",
	    "id": 1,
	    "name": "Pete"
	    "type": "contacts"
	  }
}
```

A collection of resources
```
{
  "data": [
	  {
	    "admin": false,
	    "age": 20,
	    "email": "person0@test.com",
	    "id": 1,
	    "name": "Pete"
	    "type": "contacts"
	  },
	  {
	    "admin": false,
	    "age": 20,
	    "email": "person1@test.com",
	    "id": 2,
	    "name": "Jane"
	    "type": "contacts"
	  }
  ]
}
```

http://jsonapi.org/format/

> Top Level
> 
> A JSON object MUST be at the root of every JSON API response containing data. This object defines a   document's "top level".
> 
> The document's "primary data" is a representation of the resource, collection of resources, or resource  relationship primarily targeted by a request.
> 
> A document MUST contain either primary data or an array of error objects.
> 
> Primary data MUST appear under a top-level key named "data". Primary data MUST be either a single  resource object, an array of resource objects, or a value representing a resource relationship.

**Comment by samselikoff** [comment]
This is absolutely in the roadmap, but will be at the serializer level rather than the factory level. Factories are only about getting data into the db - about setting up your "server" state.

Once the ORM + relationships are done, we'll be able to tell if you return a model from your route handler. That model would then pass through a serializer. It's at this point where you can say which related models to include, which attrs to include, the format to serialize in (AMS, JSON API, ..) etc.

Relationships will also make it easy for factories to create related data, but again they're about filling your db with the right data, not the actual API part.

**Comment by eccegordo** [comment]
ah ok makes sense

**Comment by lessless** [comment]
is it possible to return JSON-API compatible payload out of the box now?

**Comment by brettchalupa** [comment]
@lessless See [Working with JSON API](http://www.ember-cli-mirage.com/docs/v0.1.x/working-with-json-api/) in the docs. The serializer layer is coming, but it has not landed yet. If you follow that guide it will work w/ the JSON API Adapter & Serializer w/ Ember.
