### ISSUE TITLE
How to add serializer mixins

### ISSUE THREAD

**Issue by mkay581** [samselikoff/ember-cli-mirage#1304]
Sorry if this is the wrong place to post this but I have addon that uses mirage but I'd like to expose helper Serializer mixins to the consumer that are based off of mirage's Serializers. How would I go about doing this? I've tried passing multiple arguments to the serializer's `extend()` method but my `serialize()` method is never called.

```js
// tests/dummy/mirage/serializers/my-serializer.js
import ApplicationSerializer from './application';
import MySerializerMixin from 'myaddon/mixins/mirage/serializer-mixin'; //same mixin exposed to consumer

export default ApplicationSerializer.extend(MySerializerMixin, {

  serialize() {
    // super call here? or prototype call?
    // do custom serialize stuff here after MySerializerMixin's serialize logic
  }
});
```

**Comment by eliasmelgaco** [comment]
Hy @mkay581. Maybe this can help you

http://www.ember-cli-mirage.com/docs/v0.4.x/serializers/

**Comment by mkay581** [comment]
Yes that page is helpful however it does not explain how to add mixins to the mirage serializer. How would I add a mixin to the serializer?

**Comment by samselikoff** [comment]
@mkay581 Sorry for the delayed response!

I know it's confusing but Mirage's classes do not use the Ember Object model, so `.extend()` does not behave the way it does when using `Ember.Component`, `Ember.Route` and so on.

I want to update Mirage's classes to ES6 classes eventually but today they use an `extend` module borrowed from Backbone.

I would check the guides to see how to call `super()` (it's a bit involved), and then from there figure out the best way to share Serializers with your consumers.

I'll close this for now because I want to keep these issues actionable - but please feel free to ping me back if you want to follow-up!

**Comment by janmisek** [comment]
The problems with mixin is that it does not actually know its parent. I have my own workaround

My workaround relies on es6 classes which are basement for classic `Class.extend` in mirage. 

Here is my example:

```
# timestampable-mixin.js for models
export default (superclass) => class extends superclass {

  constructor() {
    super(...arguments);
  }

  save() {
    // created at
    if (!this.attrs.createdAt) {
      this.attrs.createdAt = new Date();
    }
    
    // updated at
    this.attrs.lastModifiedAt = new Date();

    return super.save(...arguments);
  }


};
```

```
# model.js model file using the mixin

import { mixin } from 'addon-toolbox/javascript/es6-classes';
import TimestampableMixin from "../toolbox/model/timestampable-mixin";

export default class ProductInstance extends mixin(Model, TimestampableMixin) {

  getSelfLink() {
    return {href: `/build-management/products/${this.productId}/productInstances/${this.id}`};
  }

}

```

```
# implementation of `mixin` function

export function mixin(Klazz, ...Mixins) {
  return Mixins.reduce((Klazz, Mixin) => Mixin(Klazz), Klazz);
}


```
