### ISSUE TITLE
Documentation clarification

### ISSUE THREAD

**Issue by kumy** [samselikoff/ember-cli-mirage#1340]
Reading the page http://www.ember-cli-mirage.com/docs/v0.4.x/models/, there seems to have two contradictory information.

At the very beginning of the article, there is this Note:
> Note - if you’re using Ember Data and version 0.3.3 of Mirage or later, models will be detected and auto-generated for you in-memory, so you don’t need to define the files yourself.

And just on the right, there is message:
> As a clarifying point, Mirage models know nothing about your Ember application, including any Ember Data models you may have defined.

As I understand them, those sentences are contradictory. I hope the note on the right is outdated ;)

---

![screenshot from 2018-07-08 14-12-37](https://user-images.githubusercontent.com/176794/42419613-0073aaca-82b9-11e8-9356-9da0fa23fdaa.png)

**Comment by samselikoff** [comment]
Haha – you are certainly right that this is confusing!

The clarifying point on the right was added because people were (understandably) getting confused about Mirage models and Ember Data models when Mirage's ORM was first released. Mirage's ORM was added to help folks write less code for their mock server & make the route handlers more powerful. It relies on a schema that was originally defined by creating new files under `/mirage/models`.

The confusion was from people doing things like creating Mirage models and passing them into components in integration tests. Mirage models should never "cross the boundary" of the network, they just exist to help folks write their mock servers.

Once we added the autodiscovery feature, Mirage was now able to read in its ORM schema by looking at the host app's Ember Data models & relationships. However, this is just used to "bootstrap" Mirage with the knowledge needed to set up its ORM. After that process happens, it's still true in some sense that Mirage knows nothing about the host Ember app, or even the fact that it's sending responses to an Ember app at all.

We should definitely clarify this! Would you be up for helping out?

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/commit/6c111a0b0c4d632b7eb12e093521965d3731a5da closes
