### ISSUE TITLE
factories are ignored if record is created using pluralized model name

### ISSUE THREAD

**Issue by jelhan** [samselikoff/ember-cli-mirage#1357]
`server.create()` supports creating record with singular and pluralized model names. But if pluralized model name is used, a factory for that record is ignored.

Assume having a model `post` with a factory defined.
```
server.create('post'); // factory is used
server.create('posts'); // factory is not used
```

Reproduction: https://ember-twiddle.com/c70f9095edc4d2608de07ea048e2dee6?openFiles=mirage.scenarios.default.js%2C

Please also note that a working twiddle does not require that much code as current boilerplate twiddle included in `ISSUE_TEMPLATE.md`. Maybe that one should be reduced to make it easier for new contributors.

**Comment by samselikoff** [comment]
This is definitely confusing behavior - thanks for the issue!

I'm actually leaning towards throwing an error here instead of just working for the pluralized case. After all, we have `createList`, so `create('posts')` would never make sense from the perspective of readability/clarity.

If we call `server.create('foo')` on a model that doesn't exist, we throw an error, so I think we should do the same here. We can add a message in the assertion that says "Remember to pass singular model names to server.create."

**Comment by jelhan** [comment]
This issue is the same for `createList` cause that one just passes the input down to `create`: https://github.com/jelhan/ember-cli-mirage/blob/302dcd137c7e3f2972f4287f624d8666bfb1f5c6/addon/server.js#L446 #1358 is fixing it for both.

**Comment by samselikoff** [comment]
What I mean is I think we should throw an error (user `assert()` to ensure the argument passed in corresponds to a singularized model name) instead of coerce it for them. I think it'd be confusing to open a codebase and see `server.create('user')` and `server.create('users')` in it.

There's also the edge case where there are two different model names where one happens to be the pluralized version of the other, e.g. something like `data` and `datum` or `serie` and `series`.

**Comment by jelhan** [comment]
So you are talking about also not supporting `server.createList('users', 1)`? Maybe I just got confused by your first post. I just wanted to clear out, that this bug is related to `server.create()` as well as `server.createList()`. Actually I got bitten by it using `server.createList()` but just wanted to simplify for reporting.

**Comment by samselikoff** [comment]
Correct, let’s not support it, and we can use assert to throw a message
letting people know what’s going on. Does that make sense?

**Comment by jelhan** [comment]
Agree. Reducing unneeded complexity is always good. But I'm not quite sure how to best assert this cause `create` method seems to be quite complex having at least three cases to deal with and utility functions `toCollectionName` and `toInternalCollectionName` can't be used cause they pluralize `type`. (That's the reason why basic functionality is working fine and only factory is ignored if pluralized type is passed to `server.create()`). Would be nice if you could take over.

**Comment by barryofguilder** [comment]
I just upgraded to 0.4.10 and I'm running into the following issue. I have a model that has a plural name, `channel-notifications`, that is plural because it is actually a bunch of different notifications for a channel. I get an error where I'm calling `server.create('channel-notifications')` now that says:

"You called server.create('channel-notifications') but no model or factory was found. Make sure you're using the singularized version of your model."

I can make it singular for `server.create` and it works, but it's a little odd because the Ember model is plural and you have to specify it singular just for Mirage.
