### ISSUE TITLE
Use Factories in development

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#136]
Here's how I see this working. If Mirage finds a `/mirage/scenarios/default.js` file, it will use that to seed its database during development, rather than the fixture files.

This file will export a function that takes one argument, `server`:

```js
// app/mirage/scenarios/default.js
export default function(server) {
  var contact = server.create('contact');
  server.createList('comment', 20, {contact_id: contact.id});
}
```

Changes needed:

- [x] Add a line to the initializer [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L13) to look for a function at `/app/mirage/scenarios/default.js`. Call this `var scenariosMap` (we plan to support multiple scenarios later on).
  - simply define a new `utils/read-scenarios` utility function. Alternatively, read-x should eventually be refactored.
- [x] Update the initializer [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/app/initializers/ember-cli-mirage.js#L25) (i.e. in non-testing environments) to check if `scenariosMap` exists. If so, invoke it, passing in the server; otherwise load the fixtures into the db.

**Comment by g-cassie** [comment]
+1  Two thoughts below about future possibilities though I think this approach would work perfectly as a starting point.

If you had a huge fixture-set you may want to be able to split your scenarios among multiple files like you do right now with fixtures.  I presume because `scenarios/default.js` is just a function you can spread your code over subdirs and import - perhaps something like `/scenarios/default/*.js`?

My other thought is it would be nice to have an efficient way to build a realistic looking dataset.  For instance if you want 20 comments that have realistic text, it would be nice to be able to feed in a list of pojos with `comment.body` and `comment.title` values, but still be able to specify `comment.contact_id` once.  Again, because `default.js` is a script I guess you can just write some simple loops to get this kind of functionality.

**Comment by samselikoff** [comment]
Yep, both great points. I want to use FakerJS to be able to write factories like

```js
export default Mirage.Factory.extend({
  first_name: Faker.firstName,
  last_name: Faker.lastName
});
```

and these would generate realistic fake data.

For now I think we would leave splitting the scenarios among multiple files to the developer. `/default.js` would be the function read in, and eventually I'd like to support loading different scenarios, perhaps via query params or some other mechanism.

**Comment by g-cassie** [comment]
Anything I can do to help with this?

**Comment by samselikoff** [comment]
sure! if you'd like to give the implementation a stab, I could talk you through it in a PR

**Comment by g-cassie** [comment]
K I'll give it a shot

**Comment by samselikoff** [comment]
026a32d7b15388a0658cb3529a9d006266da30a4 closes.

To use factories to seed your development database, create the file `/scenarios/default.js` and export a function:

```js
// /mirage/scenarios/default.js
export default function(server) {
  server.createList('contact', 20);
}
```

This scenario will be loaded during development only, so it won't affect your tests.
