### ISSUE TITLE
Cannot upgrade from 0.0.27 to 0.0.28 (nor 0.0.29)

### ISSUE THREAD

**Issue by Serabe** [samselikoff/ember-cli-mirage#137]
My current models are as follow:

> CatalogMetadata -> belongsTo(async,polymorphic) -> Catalog
> Catalog -> hasMany(async,polymorphic) -> Sections

Previously, my config looked like:

```js
this.get('/api/catalogMetadata/:id', ['catalog-metadatas']);
this.get('/api/specificClassOfCatalog/:id', ['catalogs']);
this.get('/api/specificClassOfSection/:id', ['specific-class-of-sections']); // on for each specific class
````

After upgrading to 0.0.29 (though the breaking change was in 0.0.28), I had two problems:

1. I need to use camelize names when the model's name has more than one word. Since both Ember Data and Ember CLI are moving/have moved to dasherized strings, is this correct?

2. I'm also getting calls to the generic section endpoint for the polymorphic resources. Instead of `/api/specificClassOfSection/:id`, I'm getting calls to `/api/sections/:id`.

Are these bugs or features? I saw no reference to these changes in the changelog, though.

**Comment by samselikoff** [comment]
This sounds frustrating, sorry you're running into problems. I really appreciate you digging + opening up an issue!

1. When you say you need to use camelCase names, which part are you referring to? I see some camelCase values in your Mirage config, but those are the paths to your API. Could you clarify, perhaps by showing what you had to change your config to after upgrading?
2. Are you saying your Ember app is now requesting `/api/specificClassOfSection/:id` instead of `/api/sections/:id`? If so Mirage shouldn't have affected this at all, since Mirage sits outside of your app.

**Comment by Serabe** [comment]
Please, don't apologize: you are doing an amazing job!

1. The changes would be as follow: `this.get('/api/catalogMetadata/:id', ['catalogMetadatas']);`, then move the fixture from `catalog-metadatas.js` to `catalogMetadatas.js`. I saw that in the [get handler](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/shorthands/get.js#L112) collection is getting the camelized name, and not the dasherized one.

2. If I upgrade, and fix some names (like the one in point 1), then mirage raises some errors about `/api/sections/:id`. It is strange but the only thing that changed in my package.json was mirage, so no clue why this is different.

**Comment by samselikoff** [comment]
For 1, collection is not camelized, it just pluralizes it. I'm actually still not sure the behavior you're expecting with

```js
this.get('/api/catalogMetadata/:id', ['catalogMetadatas']);
```

Typically when you have a route with `:id` you want to return a single record whose `id` matches. If you wanted to find a `catalogMetadata` by id you could just use

```js
this.get('/api/catalogMetadata/:id');
```

or specify the type explicitly with

```js
this.get('/api/catalogMetadata/:id', 'catalogMetadata');
```

In your example you pass an array to the shorthand, so that's actually just going to return the entire collection of `catalogMetadata` records - is that what you want? What's the behavior you're going for?

BTW you can always write the function manually

```js
this.get('/api/catalogMetadata/:id', function(db, request) {
  return db['catalog-metadatas']
});
```

so you can leave your filenames hyphenated. But I'm still not understanding exactly what behavior your going for.

**Comment by g-cassie** [comment]
I'm finding naming is a bit confusing as well.  It's not quite clear when to use camelized/dasherized/underscored.  I definitely think that all filenames should be dasherized to match ember-cli.  My understanding is that the keys on `db` are taken from the filename - so perhaps the shortform functions should automatically dasherize the url before looking up the db? 

For example all three of these statements:
```js
this.get('/fruit_basket/');
this.get('/fruit-basket/');
this.get('/fruitBasket/');
```
Should result in this:
```js
this.get('/(fruit_basket|fruit-basket|fruitBasket)/', function(db , request){
  return db['fruit-basket'];
});
```

**Comment by samselikoff** [comment]
Yes this is confusing, originally it was to make it easy to load data into your tables (like you say, underscore filename = underscore db table name). Once we get serializers, everything will be dasherized, and if your API does underscore you'll configure that in the serializer.

**Comment by g-cassie** [comment]
Ok, is there any point in a PR to implement this behaviour immediately or are serializers landing in the near future?

**Comment by samselikoff** [comment]
They're blocked by relationships, which are still a few weeks out.

I suppose we could add a pr to support a single default serializer (i.e. not model-specific) that would just iterate through all the keys and either camelCase or snake_case them. This would involve standardizing all js prop names (always camelCase, including table names etc.).

**Comment by g-cassie** [comment]
I think a note in the docs about how to name things would go a long way. 

Not being able to use the shortcuts due to having underscored urls but wanting to use dasherized filenames is a little bit of a frustration but certainly manageable.

I'd be happy to work on a PR but think it makes sense to keep it minimal at this point given it will all change soon anyway.

**Comment by samselikoff** [comment]
Yep I agree. You could do `this.get('/some_users', 'some-users')` for now, to have underscore url but refer to a dasherized collection name.

**Comment by samselikoff** [comment]
Same with the other shorthands, you can optionally specify collection name (which in your case would be the dasherized name): http://www.ember-cli-mirage.com/docs/latest/shorthands/

**Comment by g-cassie** [comment]
Ahh okay missed that - that will help.  I will try to submit something on naming conventions to the gh-pages branch.

**Comment by samselikoff** [comment]
I think the new [serializers in 0.2.0](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/) address this issue. Closing for now, feel free to reopen in case you have questions!
