### ISSUE TITLE
Too much recursion

### ISSUE THREAD

**Issue by ioleo** [samselikoff/ember-cli-mirage#1372]
I've got Ember model `category`:

```
// pseudocode
category-model {
  parent: belongsTo('category', { inverse: 'children' }),
  children: hasMany('category', { inverse: 'parent' }),
}
```

I've created a similar mirage model for it, and then in mirage factory
```
// pseudocode
category-factory {
  parent: association()
}
```

As soon as I added `association()` I got error `too much recursion`.
How should I define such relationship in Ember Mirage?

**Comment by samselikoff** [comment]
@ioleo The problem is if you use `association()` on the root of your factory, _every_ `category` that gets created will try to create a parent `category`, ad infinitum.

One solution is to put the association under a trait:

```js
Factory.extend({

  withParent: trait({
    parent: association()
  })

})
```

That way you can call `server.create('category', 'withParent')`, and only the top-level category will get its parent created.

The other is to just create the parent manually:

```js
let parent = server.create('category');
let child = server.create('category', { parent });
```

Make sense?

**Comment by ioleo** [comment]
@samselikoff Thanks, it does make sense indeed.
