### ISSUE TITLE
Using `normalizedRequestAttrs` in a route handler when path doesn't match model name fails

### ISSUE THREAD

**Issue by barryofguilder** [samselikoff/ember-cli-mirage#1384]
I just updated from Mirage 0.4.7 to 0.4.9 and I'm seeing an issue with a particular route handler of mine. I have the following route handler:

```javascript
this.put('/Channels/Edit/:id', function({ channels }, request) {
  let id = request.params.id;
  let attrs = this.normalizedRequestAttrs();

  ...
});
```

When the route handler gets to `this.normalizedRequestAttrs()`, it blows up and gives me the following error: "Model not registered: edit"

 Digging into this, I found that inside the `normalizedRequestAttrs` function, it is generating the model name based on the path. This line isn't new, but after it calls `this._getAttrsForRequest(request, modelName);`, it's using the model based on the route handler path to get the relationship information ([see this line](https://github.com/samselikoff/ember-cli-mirage/blob/v0.4.9/addon/route-handlers/base.js#L62)), which causes the process to fail.

A temporary workaround I'm able to do to fix this is by setting the `path` in my route handler so it uses the correct model name.

```javascript
this.put('/Channels/Edit/:id', function({ channels }, request) {
  // Adding this line forces it to use the correct model name
  this.path = '/Channels';

  let id = request.params.id;
  let attrs = this.normalizedRequestAttrs();

  ...
});
```

**Comment by barryofguilder** [comment]
I'm wondering if a way to fix this would be to introduce the model name parameter like you do for the shorthand version of the `post` request. Something like:

```javascript
this.put('/Channels/Edit/:id', 'channel', function({ channels }, request) {
  let id = request.params.id;
  let attrs = this.normalizedRequestAttrs();

  ...
});
```

**Comment by samselikoff** [comment]
yikes. This definitely shouldn't have been a breaking change, sorry about that.

I think I'd rather see modelName as an argument to `normalizedRequestAttrs`. But let me see if I can fix this bug first without having to change anything.

I wonder how it was detecting the modelName correctly before?

**Comment by samselikoff** [comment]
@barryofguilder I'm adding an optional argument to `normalizedRequestAttrs` so you can specify the modelName.

It was actually a "bug" that this worked previously... if you ever tried to pass relationship data long with the payload it would have broken. That's because `normalizedRequestAttrs()` was meant to be like a "this.super()" call for shorthands, and shorthands work by using conventional paths (so Mirage can infer the modelName from the path). With routes like `/users/create` it can't do that, so I'm adding an optional `modelName` param for routes like these.
