### ISSUE TITLE
Build fails on mirage 0.4.9 on heroku review apps

### ISSUE THREAD

**Issue by juanazam** [samselikoff/ember-cli-mirage#1436]
Hello,

I upgraded an app from mirage 0.2.9 to 0.4.9 without any issues locally.
The project uses heroku's review apps and it's using this buildpack https://github.com/heroku/heroku-buildpack-emberjs.

The problem arises when the app is being built on heroku when creating the review app.

The build process fails with the following message:

`ENOENT: no such file or directory, lstat '/tmp/build_bb507e57cd9d425d8bd759f7ce8a1a7d/mirage'`

The `config/environment` file from the app looks similar to this:

```
if (environment === 'development' || environment === 'production') {
    ENV['ember-cli-mirage'] = {
      enabled: false,
      excludeFilesFromBuild: true
    };
  }
```

**Comment by juanazam** [comment]
@samselikoff more information on this:

I think this is related to: https://github.com/samselikoff/ember-cli-mirage/pull/1236

Seems that noop initializer is not working correctly on heroku

**Comment by samselikoff** [comment]
Hmm... I just rewrote that code in https://github.com/samselikoff/ember-cli-mirage/pull/1410, any chance you could try `master`? (Though I don't know if it will fix it because it was mostly changing the broccoli code, the actual "built" file should be the same...)

The other thing you can do is use the [addon blacklist](https://ember-cli.com/user-guide/#whitelisting-and-blacklisting-assets) to completely exclude Mirage in production/dev.

**Comment by samselikoff** [comment]
https://github.com/samselikoff/ember-cli-mirage/releases/tag/v0.4.10 released, give it a shot!
