### ISSUE TITLE
No CHANGELOG

### ISSUE THREAD

**Issue by scottkidder** [samselikoff/ember-cli-mirage#1442]
Hello,
Shouldn't there be somewhere to see a list of changes between releases? I understand this is supposed to be in GitHub releases, but there is nothing there for 0.4.10. The number of changes between 0.4.9  and 0.4.10 is significant and I immediately ran into issues with no where to look to see what may have caused them.

**Comment by samselikoff** [comment]
Sorry about that Scott! I stopped keeping the changes in CHANGELOG because I didn't like creating new commits after a version was cut just to update the log.

My apologies for not putting any notes in the 4.10 release, but it should have just been bugfixes.

I will start putting a link to the list of commits between releases in the Release, so you can easily browse the commits.

As far as your bug(s), what are you running into?

**Comment by nathancharles** [comment]
I am also seeing issues after upgrading from 0.4.9 to 0.4.10.

> Mirage: You called server.createList('accountUsers') but no model or factory was found. Make sure you're using the singularized version of your model.
Where my model and factory are both named _account-users_.

It looks like pluralization of records changed when creating or referencing. It seems this is an unintentional change. If it is not, I agree, a changelog would be great since migrating all references like this will definitely be non-trivial for my application.

**Comment by samselikoff** [comment]
@nathancharles thanks for the report. I will change this to a deprecation and release a 4.11

**Comment by nathancharles** [comment]
great, thanks!

**Comment by makepanic** [comment]
If you want to automate the CHANGELOG part, you could follow https://www.conventionalcommits.org/en/v1.0.0-beta.2/ as commit convention and use something like https://github.com/conventional-changelog/standard-version to bump npm version, tag version and generate updated CHANGELOG in one step.

It works pretty well for us in various projects.

**Comment by scottkidder** [comment]
I've grown to love conventional commits as well, it seems to help out even on personal projects.

**Comment by kratiahuja** [comment]
@samselikoff do you need help with changing the error to deprecation? I can pick this up as this keeps breaking for us and we have to remember to pin it to 0.4.9.

**Comment by samselikoff** [comment]
@kratiahuja Think I'll be able to get to it tonight

**Comment by samselikoff** [comment]
Just opened PR https://github.com/samselikoff/ember-cli-mirage/pull/1452

**Comment by kratiahuja** [comment]
Thanks @samselikoff

**Comment by samselikoff** [comment]
@kratiahuja @nathancharles I've just released [0.4.11](https://github.com/samselikoff/ember-cli-mirage/releases/tag/v0.4.11), could you give it a shot and let me know if it fixes it?

**Comment by samselikoff** [comment]
Make that 0.4.12 :)

**Comment by kratiahuja** [comment]
Thanks a lot @samselikoff

**Comment by scottkidder** [comment]
The details on the latest releases look great! Thanks for being responsive on this @samselikoff

**Comment by nathancharles** [comment]
Thanks @samselikoff !
