### ISSUE TITLE
Consider locking down dependencies to patch versions only

### ISSUE THREAD

**Issue by kevlarr** [samselikoff/ember-cli-mirage#1470]
Our project relies on Mirage locked to `0.4.0` which has a dependency of `"ember-lodash": "^4.17.3"`

My coworker built awhile ago, so `npm install` pulled in Mirage with `ember-lodash` version `4.18.0`. Building today, `npm install` pulled the same version of Mirage but with `ember-lodash` version `4.19.4` instead, which itself pulled another dependency that is incompatible with Ember 2.11 (requiring 2.13+).

Using `"^xx.yy.zz"` versioning for [all dependencies in package.json](https://github.com/samselikoff/ember-cli-mirage/blob/master/package.json#L37) effectively means that *patch* versions of Mirage will update *minor* versions of dependencies, which is against expectation.

I propose that dependencies be versioned to allow flexibility at the patch level only, eg.`"~xx.yy.zz"`.

**Comment by Turbo87** [comment]
@kevlarr I would disagree with this suggestion. The root cause of your problem is that ember-lodash did not bump their major version when updating their Ember requirements. IMHO it would need to be fixed over there.

The other thing is that I would suggest that you use a lockfile (yarn or npm), in which case you would have been able to stay on the ember-lodash version that worked for you. Even now, with yarn resolutions you could manually overwrite the version requirement as a short term workaround.

Ultimately I would suggest updating Ember CLI though, you could even update it without updating Ember itself.

**Comment by kevlarr** [comment]
You're disagreeing on the basis that ember-lodash only updated their minor version when a dependency of theirs updated a major version (valid criticism). How is that different from patch versions of Mirage being able to pull in minor version updates of dependencies? It feels like we're both following the same logic here.

FWIW yes, you're absolutely right - we *should be* using lock files, and ember-lodash *should* have not changed versions at the minor level.

**Comment by samselikoff** [comment]
Yeah. Tricky thing is, say Mirage bumps its version of `chalk` from `1.1.1` to `1.1.2`. Semver is really just a convention, not a guarantee, so that could break the world. In this case, what is the appropriate response?

Users can always use `resolutions` to work around this. And in the meantime, I guess the best path forward is to communicate to the author that they broke on a non-major version?

**Comment by ef4** [comment]
I agree with @Turbo87 and want to add an even stronger reason: it's a *bad* thing for a library (including an ember addon) to use stricter dependencies than absolutely necessary. I think most ember addons already use dependencies that are _too strict_, because both `^` and `~` probably cause many addon authors to rule out earlier versions of their dependencies that actually still work. It would be better to use `>` in a lot of cases.

The reason this matters is deduplication. Today's deduplication story in ember-cli is... weirdly not constantly on fire, given that it mostly works by accident. Going forward I expect to have much more precise control, which is going to bring to light all the duplication horrors that are hiding in people's apps.

_Libraries_ should be very lenient while _apps_ should be very strict. As in, apps definitely need to use a lock file. Nothing else can really save you from upstream bugs striking at random when you don't want to deal with them. 

Stricter library deps are both ineffective (because bugs can strike even in semver patch releases), and actively harmful (because they reduce in greater dependency duplication).

**Comment by Turbo87** [comment]
>  It would be better to use `>` in a lot of cases.

I disagree on that part though. See https://github.com/request/request-promise/pull/299 for reasons why that is not a good idea.

**Comment by ef4** [comment]
Sure, amend what I say from `>1` to `>1 <3`.

**Comment by kevlarr** [comment]
@samselikoff 

> Semver is really just a convention, not a guarantee, so that could break the world. In this case, what is the appropriate response?

Ah okay, that's a great point (and I think was the essence of what @Turbo87 was telling me and I was misunderstanding)

**Comment by Turbo87** [comment]
> to `>1 <3`.

isn't that essentially the same as `^2` though? 😉

**Comment by samselikoff** [comment]
> _Libraries_ should be very lenient while _apps_ should be very strict.

This is the part I always remember, and while it's neither consistently followed nor respected by tooling in the large, it seems like a good general approach.

Thanks @ef4 and @Turbo87 for chiming in & sharing your thougths.

@kevlarr – I fail to understand this stuff every other month when new issues crop up. It's an absolute nightmare as far as I'm concerned, and extremely prohibitive to the powerful abstractions that could exist in the ecosystem were it solved by the tooling layer. I'm not really sure about general best practice advice in the future because I often hear different advice from knowledgable people.

Sorry you ran into the bug but resolutions is probably your best short-term fix, barring the ability to go ahead and upgrade!

**Comment by ef4** [comment]
I meant `>=`. I want to include the 1.x series too.

The microlanguage for semver checking is not something I trust myself to get right without testing:

```
> require('semver').satisfies("1.0.1", ">=1 <3")
true
> require('semver').satisfies("2.0.1", ">=1 <3")
true
```

**Comment by Turbo87** [comment]
we started doing something like https://github.com/simplabs/ember-simple-auth/blob/master/package.json#L40 but that is also causing other issues, so I'm not sure how useful that is in practice...

**Comment by kevlarr** [comment]
> Libraries should be very lenient while apps should be very strict.

I like this, it's not something I had really thought through enough in the past but it *does* seem like a great general approach, after following this conversation.

**Comment by samselikoff** [comment]
> but that is also causing other issues

@Turbo87 what other issues if you don't mind me asking?

**Comment by samselikoff** [comment]
@Turbo87 I see. Is `ember-cli-dependency-lint` our best guard against this for now?

Is this why `ember-jquery` has that `treeForVendor` code, because that's the only way to truly ensure there's no duplication?

**Comment by Turbo87** [comment]
> Is `ember-cli-dependency-lint` our best guard against this for now?

yeah, that should at least warn you about the problem if you run into it

> Is this why `ember-jquery` has that `treeForVendor` code, because that's the only way to truly ensure there's no duplication?

idk, sorry
