### ISSUE TITLE
Mirage included in production build.

### ISSUE THREAD

**Issue by erichonkanen** [samselikoff/ember-cli-mirage#1789]
With the following configuration settings mirage `v1.1.0` is included in the production build running `ember build --environment=production`:
```
    'ember-cli-mirage': {
      directory: 'app/mirage',
      excludeFilesFromBuild: (environment === 'production'), // tried with and without this line.
    },
```
Moving mirage to live at the root as /mirage properly excludes it.

Is this a problem with mirage or how ember-cli behaves?

**Comment by samselikoff** [comment]
I'm guessing it's ending up in the `app` tree due to Ember CLI's conventions – anything placed in `app` ends up there by default.

We could update Mirage to filter this out based on the option but the path of least resistance would be to move it to the root (which is the default).

You could also write your own Broccoli code to filter out `app/mirage` in your app's `ember-cli-build.js` file.

**Comment by erichonkanen** [comment]
ok gotcha, I figured as much and will just take path of least resistance :) I originally moved it within app/ to declutter our root but not big deal
