### ISSUE TITLE
setting headers

### ISSUE THREAD

**Issue by sebyx07** [samselikoff/ember-cli-mirage#186]
how can i set headers in the response ? i need to set cookies

**Comment by samselikoff** [comment]
You use Mirage.Response. Check the example here: http://www.ember-cli-mirage.com/docs/v0.1.x/routes/#function-handler.

**Comment by sebyx07** [comment]
thanks!
can you give me an example of setting cookie header, i tried 
```javascript
    {'set-cookie': 'user_id=1'}
    {'Set-Cookie': 'user_id=1'}
```

but none of them work

**Comment by samselikoff** [comment]
Ah, I'm not sure if this would work from directly within Mirage actually, since setting cookies is really a browser-level thing, and with clientside mocks the browser never really sends an xhr. I think you'd have to do a bit more research on this to find out. Basically, see if it's possible to set cookies with javascript.

**Comment by blimmer** [comment]
@sebyx07 any update on this?

**Comment by samselikoff** [comment]
There's now a cookbook entry on this: http://www.ember-cli-mirage.com/docs/v0.1.x/simulating-cookie-responses/
