### ISSUE TITLE
Support single-use server endpoint overrides

### ISSUE THREAD

**Issue by ronco** [samselikoff/ember-cli-mirage#194]
It would be ideal to temporarily override server endpoints to return an error, and then reset back to the default behavior provided in `config.js`.

The use case is writing acceptance tests to assert the UI recovers from intermittent server errors.

An example acceptance test would be:

```
visit('/posts/1');
server.forceError('post', '/comments');
fillIn('#comment', 'Hello world');
click('#submit');
andThen(function() {
  assert.equal(find('.error-field').text(), 'Sorry something went wrong, please try again.');
});
click('#submit');
andThen(function() {
  assert.equal(find('.success-field').text(), 'Thanks for your comment')
});
```

**Comment by ronco** [comment]
We are doing this with some home grown helpers (seen in this [gist](https://gist.github.com/ronco/ffaa1c7256990529068b)) that capture the default pretender handler for resetting after use.

The api could probably be cleaned up a bit if directly integrated into `Server`.

**Comment by samselikoff** [comment]
Thanks for kicking off this discussion! I'm wondering if `forceError` is too specific - maybe you want to force something else temporarily, and also have more control over the error code. Maybe we should generalize it to something like

```js
server.override.post('/comments', {error: 'message'}, 404);
server.override('post', '/comments', {error: 'message'}, 404); // or this syntax
```

That way you can use the normal routing api in your temp override. Default would be once, need to think of an api to allow multiple overrides.

```js
server.override('post', '/comments', {error: 'message'}, 404); // single override
server.override(3, 'post', '/comments', {error: 'message'}, 404); // next 3 requests error. is this api necessary?
server.override.twice('post', '/comments', {error: 'message'}, 404);
```

**Comment by samselikoff** [comment]
Only problem is `override` doesn't suggest the old route handler will be restored. Need to think of another name.

```js
server.temp('post', '/comments', {error: 'message'}, 404);
server.tempOverride('post', '/comments', {error: 'message'}, 404);
server.handleNextRequest('post', '/comments', {error: 'message'}, 404);
server.nextRequest('post', '/comments', {error: 'message'}, 404);
server.next('post', '/comments', {error: 'message'}, 404);
server.forNext('post', '/comments', {error: 'message'}, 404);
```

Thoughts? Other ideas?

**Comment by ronco** [comment]
I agree override could give the wrong impression. Maybe just 'force', but
I'm ok with your other ideas.
I'm not sure of the need for multiple, but it might be nice to set
sequentially. I'm thinking along the lines of
server.force(1, 'post' ...); // set second response zero based index

**Comment by elucid** [comment]
@ronco @samselikoff I've been noodling around with something similar for the purpose of avoiding re-implementing complicated endpoints in mirage.

For instance, let's say I am writing an acceptance test for a part of an application that sends queries to the backend API to filter a list of results. Currently I have to seed the database with factories, and then in the mirage request handler, iterate through various records in the database, possibly fetch related records involved in comparisons, assemble my result set, and return it.

I would rather just do the setup using factories, decide what some endpoint should return given my factory setup, and then call something like `server.queueResponse('get', '/products', [product1, product2]);` to prepare for the next request to that endpoint.

Reasoning being that what the server actually does is opaque to the acceptance tests anyway--even if my client-side re-implementation serves the needs of some particular test it doesn't necessarily replicate what the server really is doing so why not just stub it out on a per-test basis?

I'm keeping a queue for responses so that you can call `server.queueResponse` for a particular endpoint multiple times and when you request to it, there is first a check to see if there are any queued responses. If any exist, the first one is popped. If the queue is empty, default to the function defined in `config/mirage.js`.

**Comment by ronco** [comment]
Hey @elucid that sounds like a very similar use case to my own.  You wouldn't happen to have a gist of your queueResponse implementation would you?  I know the solution I've been using is pretty hacky and I'd be interested to see yours.

**Comment by samselikoff** [comment]
Interesting. My initial thought is that, while it's true your actual server implementation is opaque to your client, the difficulty of maintaining per-test mocks was one of the original motivating factors for creating a shared server. Certainly I think you should be pragmatic, and use whatever works best and is easiest for you - but I'm wondering if the pain here points to a need for some more base primitives, e.g. making it very easy to filter resources in your config.js.

That said, I still think there are valid reasons to override/supplement config.js's routes in an individual test, so I absolutely want to land a nice api for this.

One final thought. I eventually want Mirage to support generating some kind of "pactfile", which states the API contract of your Mirage server. If we make it simple enough to do, people may actually be able to use this in a sort of "interface test," to ensure their backend fulfills their Mirage server definition. If this ever becomes a reality, ad hoc mocks in tests would not be covered by this interface/pact test.

**Comment by elucid** [comment]
@ronco I'll open a PR with my WIP solution shortly.

**Comment by elucid** [comment]
@samselikoff I agree with that, but IMO setting up some test-specific data using factories and returning it via a one-line stub is a world away from maintaining a set of fixture files that are loaded into specific tests. Anyhow, while this facility could certainly be overused I definitely think there are valid reasons to override/suplement config.js routes for specific tests.

I'm really interested in having some sort of API contract as well. As my team is moving the majority of our  acceptance tests from cucumber to mirage, a big piece that is missing is verifying that breaking API changes still get caught.

Anyhow, I'll open a PR to show what I'm currently using. I'm still experimenting with this repo to replace some of our existing tests, so I'm not certain what is there will be the final API I will propose.

I'd love feedback if you have a chance to take a look.

**Comment by samselikoff** [comment]
Filed under the "Ability to declare temporary handlers (e.g., one-off error)" note on the Roadmap project.
