### ISSUE TITLE
Drop IE8 support

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#200]
Is this a problem?

object.defineProperty and getter/setters are key to the orm layer, so I don't think ie8 will be supported. We could maintain a version without the orm (basically mirage as it exists now), but it will be more work.

Is it worth it? I'd like to know, who's on ie8 these days?

**Comment by clekstro** [comment]
At my day job we have to support several enterprise customers, and we're dropping support for IE8 in the next few months. So I'd say it isn't worth the effort, given that it's on the way out.

**Comment by ronco** [comment]
I vote for dropping support.  They're [dropping IE8 support in ember 2.0](http://emberjs.com/blog/2015/04/20/ie8-support-update.html), so I don't think it will alarm anyone.

**Comment by samselikoff** [comment]
Thanks for the feedback y'all.

**Comment by zyllorion** [comment]
We have several enterprise customers that use IE8, please maintain something that works with 1.13 is all.

**Comment by clekstro** [comment]
Given that this addon is under `devDependencies` in `package.json`, doesn't that mean it doesn't actually ship with production builds? If so, it would only affect development/testing of IE8, which while perhaps unfortunate, is not typically how I develop. I would assume that almost all developers use a modern browser and that even staging/acceptance/QA environments using IE8 would be hitting actual endpoints and not endpoints defined in this addon.  

@zyllorion is that fair?

**Comment by samselikoff** [comment]
Except, if you wanted to run your acceptance test suite in ie8

**Comment by zyllorion** [comment]
@clekstro to a point, yes that's fair, although I do develop with CI and TDD which would of course be limited.  I think if a 1.13 version was finalised / locked then there's no issue at all. IE8 is usually the source of problems and bugs so I'd be reluctant to lose some flexibility with testing in the short term.

**Comment by jerel** [comment]
To answer the question "who is using IE8": we are. Our app is in the medical/research industry where users may be using any old browser, maybe even on dial up. I'm using Mirage and would love to be able to test IE8 (our app works fine on IE8) but I understand if it isn't feasible. Should Mirage currently work on IE8? There's lots of things broken in `/tests` in IE8 but I'm not sure yet if it's caused by babel, ember, or mirage.

**Comment by samselikoff** [comment]
I started using `Object.defineProperty` so I believe that would break ie8.

I don't think it'd be too difficult to support an ie8 compat version but, it wouldn't have the orm layer. Not sure how much this will affect things going forward (that is, I'm not sure what things ie8 would get access to beyond what's essentially in the current version of mirage).

**Comment by blimmer** [comment]
My two cents:

Since the ember community is dropping IE8 support with Ember 2.0, I think it's reasonable for future versions of ember-cli-mirage to not explicitly support IE8. That said, if there's a community of folks who rely on this package who want to take on providing polyfills to support older browsers, they can submit PRs. What do we think?

**Comment by samselikoff** [comment]
I agree
