### ISSUE TITLE
How can I use this _only_ for acceptance tests?

### ISSUE THREAD

**Issue by wayne-o** [samselikoff/ember-cli-mirage#250]
Hi, great project!

I just had a quick play about with Mirage and while it is very easy to create factories and get data out, I am only interested in faking data during acceptance tests. 

Is there a way to do this?

Cheers :)

**Comment by blimmer** [comment]
Use the 'enabled' flag in your configuration to disable everywhere but in test. Something like this:

```js
    ENV['ember-cli-mirage'] = {
      enabled: false
    };
```

**Comment by samselikoff** [comment]
Others have used Mirage for this workflow so we actually added `testConfig`, which lets you define routes that handle requests only during testing. This is nice because then you can define a new route in your main config as you develop a new feature (in case you're ahead of the API), then you can write your acceptance test for it, then once you implement the endpoint in your API you can move it from your normal config to testConfig.

Read more here: http://www.ember-cli-mirage.com/docs/v0.1.x/server-configuration/#testConfig

**Comment by wayne-o** [comment]
Brilliant!! 

Thank you guys :)
