### ISSUE TITLE
scenarios/default.js not being loaded

### ISSUE THREAD

**Issue by dagda1** [samselikoff/ember-cli-mirage#324]
I am using ember-cli 1.13.8 and ember-cli-mirage 0.1.11 and my ```scenarios/default.js``` look like this:

```
    export default function(server) {
      console.log('we do not get here');
      let subscriptionPlan = server.createSubscriptionPlan();
      let billing = server.createBilling({subscription_plan_id: subscriptionPlan.id});
      let account = server.createAccount({billing_id: billing.id});
      server.createUser({account_id: account.id});
    }
```
But it does not get called at all from my acceptance test.

Am I missing some set up step?

I've tried manually starting mirage as described [here](http://www.ember-cli-mirage.com/docs/v0.1.x/manually-starting-mirage/) but I think I'm missing something.

**Comment by dagda1** [comment]
Strangely if I don't disable it, the file does run in the development environment but it is definitely not running by default in test mode.

**Comment by samselikoff** [comment]
Yes, this is by design. If you look at the [database docs](http://www.ember-cli-mirage.com/docs/v0.1.x/seeding-your-database/#using-factories-in-development) you'll see the default scenario is for seeding your development database.

If you want some factory code to run for all tests, you could make a helper and add the call to `start-app.js`. But typically people just use the test itself and `beforeEach` to run any shared factory code.

**Comment by izelnakri** [comment]
I had tests with fixtures ajd my tests started failing after I introduced some factories with no warning whatsoever. This behavior is confusing should be changed.
