### ISSUE TITLE
Better error message for unhandled routes

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#335]
https://github.com/samselikoff/ember-cli-mirage/commit/8d4cb3ffb8a51fba2bf9248821a1b138516bdde0 added an error but for some reason the error message doesn't come through in the console:

![image](https://cloud.githubusercontent.com/assets/2922250/10809624/e5450326-7dce-11e5-851e-b3d68cac6f89.png)

we need to make the message show.

**Comment by seethemhigh** [comment]
To get the error that https://github.com/samselikoff/ember-cli-mirage/commit/8d4cb3ffb8a51fba2bf9248821a1b138516bdde0 added you have to have the route/router and model defined. Otherwise Ember throws errors, like 'there's no route/router/model defined', which stops from going further to the Mirage server. Once those are defined, the mirage error shows up. I think this is a reasonable behavior.

**Comment by samselikoff** [comment]
I don't think this is right. I see the error in the test runner, but during development the error is swallowed by the promise. Before we `console.error`ed so the user could see it; now they don't.

If the user's app weren't on Mirage (or were proxying) the console would show a console.error of the failed network request. I think we need to do something similar in development. Basically, the new `MirageError` class could `console.error` the message in its constructor, if the environment is development. Otherwise the user has no way of knowing their route failed because of an issue in their Mirage configuration.
