### ISSUE TITLE
Serializers can't actually control serialization

### ISSUE THREAD

**Issue by ef4** [samselikoff/ember-cli-mirage#387]
I'm seeing an architectural limitation with the current serializer API. Serializers don't actually get to control serialization -- there is a hard-coded `JSON.stringify` happening elsewhere. This makes it impossible to make an endpoint return any content type other than json.

I would propose renaming the current `serialize` method to `toJSON`, and adding a new `serialize` method whose default implementation is `JSON.stringify(this.toJSON())`. This also depends on cleaning up the logic in serializer-registry that doesn't belong there and move it inside the toJSON methods of the existing serializers.

**Comment by ef4** [comment]
Forgot to add: this is motivated by a real world app. I need to hit an endpoint that returns HTML, not JSON. ember-data is more than up to the task of handling these kind of legacy APIs, so I expect it's not uncommon to want to make mirage handle such responses.

**Comment by samselikoff** [comment]
Yes, this is all correct. I set up the global JSON.stringify on Pretender's `prepareBody` elsewhere, and while it is configurable in `config.js` (via `this.pretender.prepareBody`), now that we have a serializer layer it seems like they should have control over this piece of building the response.

Thanks for pointing this out! I'll think it through before releasing 0.2.0.

**Comment by samselikoff** [comment]
I haven't tackled this issue directly yet, but we had a change since you opened it. There is one final `_serialize` call to a response returned from the handler/serializer layer [here](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L212), which calls these lines: https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L198-L204.

I still need to get rid of the `error: not found` bit, but the first part will avoid stringifying the response if it's a string already. This means route handlers/serializers can return strings of csv, html, etc. (This is the context which caused someone else to change this).

This way, users can still return JS objects/arrays/etc and have them stringified, but if they return strings we'll pass them through. Do you think this is satisfactory to cover your original issue here?

**Comment by ef4** [comment]
Yes, this looks like it would satisfy my use case.
