### ISSUE TITLE
Discordance when POST url is undesrcored and resource is hypheneated

### ISSUE THREAD

**Issue by cibernox** [samselikoff/ember-cli-mirage#39]
I have a model named `StaffMember`, whose normalize name following ember-cli convections would be `staff-member`. I use rails as a backend, so my urls have to use snake case (`staff_member`)

My `app/pretender/config.js` contains this:
```js
  this.get('/staff_members', 'staff-members');
  this.post('/staff_members', 'staff-member');
  this.get('/staff_members/:id', 'staff-member');
  this.del('/staff_members/:id', 'staff-member');
  this.put('/staff_members/:id', 'staff-member');
```

The problem comes when I save a record, performing a POST request to `/api/staff_members` with a type string of `staff-members`. The data doesn't match in [this line](https://github.com/samselikoff/ember-pretenderify/blob/3211cad6305064c2c22c79d586386d8dd8de66af/addon/controllers/post.js#L18) and therefore breaks in [this other line](https://github.com/samselikoff/ember-pretenderify/blob/3211cad6305064c2c22c79d586386d8dd8de66af/addon/store.js#L52).

To make it easier, I created this little project to demonstrate the problem: https://github.com/cibernox/bug_demo

Install dependencies, run `ember serve` and go to http://localhost:4200/tests to see only one test failing.

**Comment by samselikoff** [comment]
Ok I will look at this.

Btw, you don't need to follow ember cli conventions for filenames here, because this is not really about ember cli. It uses ember cli to wire up the fake server, but it's really about your server. The idea is, replicate the actual server your ember app expects, and handle requests/responses pretending to be that server.

In this case, your server api will be under_scored names. So I would make all the data files /data/staff_members.js. Then the types should work out on their own.

Though, it seems you've still identified a bug, so I'll take a look.

Thanks!

**Comment by cibernox** [comment]
Just for the record, I followed the advice and i've found a combination of filename/config that works.

Having the fixtures in **a file following API naming** (in my case, `/app/pretender/staff_members.js`) and
this config: 

```js
  this.get('/staff_members', 'staff-members');
  this.post('/staff_members', 'staff-member');
  this.get('/staff_members/:id', 'staff-member');
  this.del('/staff_members/:id', 'staff-member');
  this.put('/staff_members/:id', 'staff-member');
```

It works. Any other combination fails either posting or getting.

**Comment by cibernox** [comment]
I correct myself. It doesn't work. I forgot to unlink my local version with the fix I've submitted.

**Comment by samselikoff** [comment]
@cibernox is this still a problem?

**Comment by cibernox** [comment]
No. Closed
