### ISSUE TITLE
Support for this._super within serializer methods

### ISSUE THREAD

**Issue by ballPointPenguin** [samselikoff/ember-cli-mirage#398]
It would be nice to be able to do:
```
import BaseSerializer from './application';

export default BaseSerializer.extend({
  serialize(response, request) {
    // something custom
    this._super(response, request);
  }
});
```

Currently, I just get
```
this._super() is not a function
```

**Comment by samselikoff** [comment]
Right now `extend` is taken from Backbone, because (1) I didn't want Mirage to rely on `Ember.Object` (idea was to be able to extract Mirage from EmberCLI Mirage) and (2) I didn't use ES6 classes since they don't support property declarations.

Backbone's docs say you should be able to explicitly call the parent, so try something like this:

```js
export default BaseSerializer.extend({
  serialize(response, request) {
    // something custom
    BaseSerializer.prototype.serialize.apply(this, arguments);
  }
});
```

**Comment by ballPointPenguin** [comment]
I'm closing this.
