### ISSUE TITLE
import-files-test-node test is broken

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#44]
changed `expect.to.include` to `expect.not.to.include` and tests still pass :dizzy_face: 

didn't catch a bug when I renamed to mirage

**Comment by marcioj** [comment]
Hi @samselikoff, sorry for that.

I got lastest version of the project, and could not reproduce this problem. Can you point out the specific test that fails when including `not` in the assertion?

Also, I must say that running `ember test` will not run the `*-test-node.js` tests. This is why I added `mocha tests/**/*-test-node.js` in the [test script](https://github.com/samselikoff/ember-cli-mirage/blob/master/package.json#L14), so you need to run `npm test` to consider all the tests.

This is also how travis is [configured](https://github.com/samselikoff/ember-cli-mirage/blob/master/.travis.yml#L20).

**Comment by samselikoff** [comment]
ahhh, ok that could have been it. I had forgotten to change `pretender` to `mirage` here:

https://github.com/samselikoff/ember-cli-mirage/commit/2c51833c3b24e7e107d4de095f73562758e3c272

I wonder if it would have failed if I ran `npm test`? Did we need mocha because we can't use qunit in node?

**Comment by marcioj** [comment]
> I wonder if it would have failed if I ran npm test?

Probably not, because the tests in addon-tree-test-node.js just verify whether the `excludePretenderDir` method is called or not. [This is a sample](https://github.com/samselikoff/ember-cli-mirage/blob/master/tests/unit/addon-tree-test-node.js#L64). So, before your commit `excludePretenderDir` was still being called, but with the old name `pretender` and the tests probably would pass. Some alternatives that comes to my mind is:

- Create a method called `miracleRootPath` which would return `<module-prefix>/mirage/`, and unit test it, so we prevent these issues in the future.

or

- Do a `ember build` in a tmp dir and check if it contents contain references of `miracle` code. Probably a regex checking for amd `define`s containing the `miracle` word. Not sure if this is the better way though.

> Did we need mocha because we can't use qunit in node?

I just used mocha as a personal preference, but I agree that is strange to have two tests frameworks in the project. A quick search showed to me this [qunit node runner](https://www.npmjs.com/package/qunit).  Should we give it a try? If so I can update the existing tests.

**Comment by samselikoff** [comment]
I see, thanks for explaining :) Let's not worry about it, eventually I want to extract the core pieces of this library into a separate Mirage project that has nothing to do with Ember. Then we could have a nicer setup and perhaps use mocha for all the tests.

Seems like for now, the `ember build` step + checking the tmp dir would be really nice.
