### ISSUE TITLE
Mapping from a collection to another escapes the Collection API

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#486]
(@ballPointPenguin raised this issue)

Here's a totally legitimate route handler:

```
this.get('/projects', (schema, request) => {
  let projectMembers = schema.projectMember.where({ userId: 12345 });
  let projects = projectMembers.map((member) => member.project);
  return projects;
});
```

but `projects` is no longer a `Collection`, so serializers break. How should we deal with this?

**Comment by samselikoff** [comment]
One option is 

```
this.get('/projects', (schema, request) => {
  return schema.project.where(p => p.projectMember.userId == '12345');
});
```

which I think requires some changes to `.where`. (where no longer simply delegates to DB collection).

**Comment by samselikoff** [comment]
Another is to have `Collection#map` check if the returned array is an array of models of the same type, and to just make a new `Collection` at that point.

**Comment by samselikoff** [comment]
I need to see how Rails deals with this.

**Comment by bekzod** [comment]
> Collection#map check if the returned array is an array of models of the same type  

I was thinking about same thing sounds reasonable to me

**Comment by mitchlloyd** [comment]
An issue with changing `collection.map` is that every array-like function that might return a homogeneous array of models would need the same treatment (e.g. `reduce`) and a user that decided to use build their own array with `forEach` and `[].push(model)` or using a lodash functions would be confused when it didn't work. 

> I need to see how Rails deals with this.

Rails [ActiveRecord::CollectionProxy](http://api.rubyonrails.org/classes/ActiveRecord/Associations/CollectionProxy.html) and [ActiveRecord::Relation](http://api.rubyonrails.org/classes/ActiveRecord/Relation.html) doesn't have any `map` method. Using `map` returns a plain array.

Because there are so many ways a user could create an array of models, it might be best to force users to keep in mind that they must return either a Model or Collection to get serialization behavior (the docs already mention this). This means for the original use case the user would need to wrap their response:

```javascript
this.get('/projects', (schema, request) => {
  let projectMembers = schema.projectMember.where({ userId: 12345 });
  let projects = projectMembers.map((member) => member.project);
  return new Collection('project', projects);
});
```

I've felt the need for a general `server.serialize` method before, so that could be the other way of handling this case.

```javascript
this.get('/projects', (schema, request) => {
  let projectMembers = schema.projectMember.where({ userId: 12345 });
  let projects = projectMembers.map((member) => member.project);
  return this.serialize('project', projects); // serialize could also take a Model or Collection without a type.
});
```

Another option would be to make the `SerializerRegistry` smart enough to detect the model type of a homogeneous array of models. I made an [implementation of that here to see what that would be like](https://github.com/mitchlloyd/ember-cli-mirage/commit/eee484b0bf3e74662eff97f542fa004ade7b4bca).

**Comment by samselikoff** [comment]
The last solution seems best. The fact that I don't remember considering it makes me worry I forgot something, as it was the first thing that popped into my head as I was reading through your comment. When I'm not as tired I'll look back through some code and issues.

If that turns out to be a robust solution, we may not even need the notion of a Collection. Working with arrays is second-nature to JS devs, and people like to use different tools for that purpose (lodash, ramda etc). It would be great if they didn't have to even think about that decision affecting the work they're doing in route handlers.

**Comment by mitchlloyd** [comment]
I just realized that one issue with trying to guess the model type of the array is that it will be impossible for an empty array. If a user returns an empty array from a route then Mirage still needs to pass that to the correct serializer.

To make collections easier to work with, Mirage could use plain arrays and add some kind of property to to identify the model type. This could handle the empty collection case, but it still means that users would need to be aware that the arrays they return from their routes are special.

```
this.get('/projects', (schema, request) => {
  let projectMembers = schema.projectMember.where({ userId: 12345 });
  let projects = projectMembers.map((member) => member.project);

  // Wrapper needed in case array is empty.
  return withCollectionType(projects, 'project');
});
```

Using plain arrays and adding an explicit `this.serialize` method to be used at the end of routes would be my preference, but that does not handle the original issue posed here and is a pretty big API change.

At this point your `where` solution that accepts a function is looking pretty good. This matches [lodash's _.filter function](https://lodash.com/docs#filter) and should be pretty easy to implement. Basically `where` would just be `_.filter` that returns a `Collection`. What do you think of that? Would be happy to put together a PR.

**Comment by mitchlloyd** [comment]
Related to adding a `serializer` method: https://github.com/samselikoff/ember-cli-mirage/issues/367

**Comment by samselikoff** [comment]
#607 closes
