### ISSUE TITLE
Serializer Embed is Confusing (or is it the Docs?)

### ISSUE THREAD

**Issue by jherdman** [samselikoff/ember-cli-mirage#513]
The 0.2.0-beta.3 docs on [Serializer 'embed'](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/serializers/#embed), it seems like this setting does absolutely nothing. I'd expect `false` to mean that I don't want to sideload records, and `true` to mean sideloading is enabled.

My tests of this beta seem to indicate that it `embed: false` does nothing. A quick survey of the tests seem to support such a conclusion too ([false case](https://github.com/samselikoff/ember-cli-mirage/blob/acacf0f4a0544cf2f843b8225899970e3e1dc155/tests/integration/serializers/base/associations/sideloading-collection-test.js#L60-L83), [true case](https://github.com/samselikoff/ember-cli-mirage/blob/acacf0f4a0544cf2f843b8225899970e3e1dc155/tests/integration/serializers/base/associations/embedded-model-test.js#L28-L49)).

Am I missing something?

**Comment by samselikoff** [comment]
In the parlance of Ember Data, **embedded** refers to the *shape* of the related data (if the included related data is embedded in the parent object, or if it is side-loaded i.e. a sibling of the parent data), rather than *whether or not* the related data is included in the response in the first place.

So an embedded record (`embed: true`) means something like 

```
{
  author: {
    id: 1,
    name: 'Link',
    blogPosts: [
      {id: 1, authorId: 1, title: 'Lorem'},
      {id: 2, authorId: 1, title: 'Ipsum'}
    ]
  ]
}
```
where a non-embedded (side-loaded) response (`embed: false`, the default) looks like

```
{
  author: {
    id: 1,
    name: 'Link',
    blogPostIds: [1, 2]
  },
  blogPosts: [
    {id: 1, authorId: 1, title: 'Lorem'},
    {id: 2, authorId: 1, title: 'Ipsum'}
  ]
}
```

Does that clear things up? Basically, the `embed: true` option was my best attempt be consistent with Ember Data (and Active Model Serializers) terminology.

**Comment by samselikoff** [comment]
Btw, if the docs are confusing we should clear this up.

**Comment by jherdman** [comment]
Ooh, yeah, that's really subtle. I think the docs can be changed to better highlight the difference. My hunch is that this confusion is compounded by the `include` flag too. I'll spend some time coming up with a pull request to clarify this once we're all said and done here.

Personally I read the embed switch as whether or not I want foreign keys in my response body versus the JSON representation of the objects in question, [a la AMS](https://github.com/rails-api/active_model_serializers/tree/0-8-stable#embedding-associations). Namely, what if I wanted a response like the below? It's not clear what combination of settings would be used to accomplish this.

```json
{
  "author": {
    "id": 1,
    "name": "Link",
    "blogPostIds": [1, 2]
  }
}
```

**Comment by samselikoff** [comment]
That would be `embed: true`. I thought that was simpler than an option like `embed: 'ids'`.

I think. Maybe you also need `include: posts`. Though it doesn't matter if the posts include `author_ids`.

**Comment by dcalhoun** [comment]
It appears the [`embed`](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.3/serializers/#embed) option [has no impact](https://github.com/samselikoff/ember-cli-mirage/blob/v0.2.0-beta.3/addon/serializer-registry.js#L46-L50) on the `JsonApiSerializer `. `serializer-registery.js` appears to `return` prior to the `embed` option check. Is that correct?

That was confusing. My confusion may be primarily rooted in my lack of knowledge of the JSON API specs, but the `embed` docs don't say anything about it not impacting the `JsonApiSerializer `. I dug through the codebase to discover that fact.

**Comment by samselikoff** [comment]
Yes, you are absolutely correct. We should clarify this. I intended the `Serializer` class included with Mirage to be used and customized most, if you're working on an app without a json:api backend, and need to recreate less standardized responses. The `embed` option doesn't really have any meaning in json:api land, since there's only one way to include related resource in a response.

**Comment by juni0r** [comment]
So is there a way to only embed the relationship ids? With `embed: true` the actual records get embedded, with `embed: false` the records are sideloaded. I'm using ActiveModelSerializer, btw.

**Comment by samselikoff** [comment]
Not an API for this at the moment, check the serializer docs for how to
override serialize and you should be able to add them yourself for now.

**Comment by typeoneerror** [comment]
I'm a little lost with the sideloading docs as well. The `include` flag seems to imply that the record will be sideloaded in the response when requesting "GET /authors/1". Does this mean it should include that data automatically? Do I still need to return the data sideloaded in my route? 

example: https://gist.github.com/typeoneerror/eb0ed30d2fd75edce351f5d83b6c591f

**Comment by samselikoff** [comment]
`include: ['profile']` means, whenever Mirage serializes a `tenant`, it will include that tenant's `profile` relationships (either sideloaded or embedded based on the `embed` option).

If you're using the serializer you should just return the model from your route handler, i.e.

```
return schema.tenants.first();
```

instead of

```
return {
  tenant: schema.tenants.first()
}
```

If you're still having problems, could you post the JSON response you're getting?

**Comment by typeoneerror** [comment]
@samselikoff my misunderstanding of the serializer layer was the cause. works as documented.
