### ISSUE TITLE
Infinite loop when loading fixtures with relationships

### ISSUE THREAD

**Issue by balinterdi** [samselikoff/ember-cli-mirage#584]
I have the following models in my app:

```js
// mirage/models/band.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  songs: hasMany('song'),
});
```

```js
// mirage/models/song.js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  band: belongsTo('band'),
});
```

And a few fixtures:
```js
// mirage/fixtures/bands.js
export default [
  { id: 1, name: 'Pearl Jam', songIds: [1, 2, 3, 4, 5] },
  { id: 2, name: 'Led Zeppelin', songIds: [6, 7, 8] },
  (...
]
```

```js
// mirage/fixtures/songs.js
export default [
  { id: 1, title: 'Daughter', rating: 5, bandId: 1 },
  { id: 2, title: 'Yellow Ledbetter', rating: 5, bandId: 1 },
  { id: 3, title: 'Animal', rating: 4, bandId: 1 },
  { id: 4, title: 'Inside Job', rating: 4, bandId: 1 },
  { id: 5, title: 'Who We Are', rating: 2, bandId: 1 },
  (...)
]
```

When I load these fixtures in my app, they throw it in an infinite loop. I tracked it down to [`model._setupRelationships`](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon%2Form%2Fmodel.js#L158).

When the first band (Pearl Jam) is instantiated, it also instantiates (and calls _setupRelationships for) the related songs and each song then seems to instantiate the band again, and then the loop restarts.

I'm not sure if there is a way around this that also makes sure the relationships are correctly set up. If I comment out the `band: belongsTo('band')` from the song model, no infinite loop is produced but at the same time `band.get('songs')` is empty.

(I'm using version 0.2.0-beta.4 and the out-of-the-box `ActiveModelSerializer` for both models)

**Comment by samselikoff** [comment]
Try removing the `songIds: []` bit from the bands fixtures, you only need the fk on the owning model

**Comment by balinterdi** [comment]
I forgot to mention I'd tried that, too. In that case, the connection is not made, so iterating through `band.songs` in the template is empty for a band that does have songs (for example, Pearl Jam above).

Interestingly, if bands have `songIds` but songs do not have `bandId`, the code also runs into an infinite loop.

**Comment by nselikoff** [comment]
I'm running into this infinite loop as well, with the same goal of being able to go both directions in the relationship. But I have a many to many relationship. 0.2.0-beta.4 and JsonApiSerializer. I'm able to make it work only with an intermediary model, which I would prefer to not have as it doesn't exist in the API I'm mocking for.

Infinite loop:

````javascript
// mirage/models/story.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  tiles: hasMany(),
});
````

````javascript
// mirage/models/tile.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  stories: hasMany(),
});
````

````javascript
// mirage/scenarios/default.js

export default function(server) {
  let story = server.create('story', {
    tileIds: [1]
  });
  let tile = server.create('tile', {
    storyIds: [1]
  });
}
````

Works, but introduces an extra model:

````javascript
// mirage/models/story.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  storyTiles: hasMany(),
});
````

````javascript
// mirage/models/tile.js

import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  storyTiles: hasMany(),
});
````

````javascript
// mirage/models/story-tile.js

import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  story: belongsTo(),
  tile: belongsTo(),
});
````

````javascript
// mirage/scenarios/default.js
export default function(server) {
  let story = server.create('story');
  let tile = server.create('tile');
  let storyTile = server.create('storyTile', {
    storyId: story.id,
    tileId: tile.id
  });
}
````

**Comment by samselikoff** [comment]
Yes - others have raised this issue before too. The problem is that even in backend systems that hide the join record from a m2m relationship, a join table is still used. Since we use models to set up the database, that's why currently the join model must be explicitly defined.

There might be an API we come up with to allow users to define m2m relationship without having to explicitly define the join model, something like Rails' `has_and_belongs_to_many`.

**Comment by balinterdi** [comment]
@samselikoff I understand why Nathan's case above makes a join model necessary but if my thinking is correct, it should not be in my case. As you say, the foreign key should be declared on the "one" end of the many-to-one relationship and it should just work. Unless I'm missing something.

**Comment by samselikoff** [comment]
@balinterdi I just tried modeled the data you put in the OP, removed the `songIds: []` piece from the band fixtures, and it's working.

Note that Mirage doesn't use .get/.set, so if you put a debugger after you `server.loadFixtures()` you should be able to do something like

```js
let pearlJam = server.schema.band.find(1);
pearlJam.songs; // array of 5 models
pearlJam.songIds; // [1, 2, 3, 4, 5]
```

Also, I wrote a template and the full thing works, fetching the data and iterating over pearl jam's songs in a template. Could you try again, perhaps on latest beta release and see if you're still running into issues?

**Comment by balinterdi** [comment]
First of all, thank you for looking into this.

I still couldn't get it to work with the fixtures though I've verified that the relationship is correctly set up by your method:

```js
> var pj = this.schema.band.find(1);
> pj.songs
Collection {0: child, 1: child, 2: child, 3: child, 4: child, modelName: "song", length: 5}
> pj.songIds
["1", "2", "3", "4", "5"]
```

However, in the template, `{{model.songs.length}}` is 0 and consequently the songs are not listed.

Could the problem be that the relationships are correctly set up between the mirage model objects, but they "break" when Ember Data records are instantiated? The actual model of my template is an ED band object, which is not identical to the mirage model I assigned to the `pj` variable above.

Actually, it seems like no ED song objects are instantiated:

![4 bands, no songs](https://monosnap.com/file/d738fmUJZDT5ccSKTNaj0z4KQZerNO.png)

I tracked it down to the [`_instantiateModel`](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/schema.js#L147) not being called for songs, only for bands. I think that is because `band.hasMany('songs')` is an async relationship, so at the the point the songs for a particular band are needed, a "backend" request to fetch these songs should be made that would instantiate Model objects from the response. However, the request is not made.

I've upgraded to the latest ember-cli-mirage version and published the code [here](https://github.com/balinterdi/rock-and-roll/tree/3437ae478a0b904f5d08a46dd50a1ab443b70df8).

**Comment by samselikoff** [comment]
If the relationship is async, does your Ember app ever make a subsequent request for the associated songs? Do you see an error in the console, or if not, what does Mirage respond with?

**Comment by balinterdi** [comment]
No, no requests are made for the associated songs, there are no errors in the console (or in the Promises tab).

**Comment by balinterdi** [comment]
FWIW, I also made an attempt with factories and a default scenario:

```js
// mirage/scenarios/default.js
export default function(server) {
  let pj = server.create('band', { name: 'Pearl Jam' });
  let daughter = server.create('song', {
    title: 'Daughter',
    rating: 5,
    bandId: pj.id
  });

  //NOTE: This should not be needed
  server.schema.song.all('song');
}
```

```js
// mirages/factories/band.js
import { Factory } from 'ember-cli-mirage';

export default Factory.extend({
  name: 'A great rock band',
});
```

```js
// mirages/factories/song.js
import { Factory } from 'ember-cli-mirage';

export default Factory.extend({
  title: 'A great rock song',
  rating: 0
});
```

The result is the same, the relationship is correctly set up between mirage model instances but no songs are displayed for the band in the template.

**Comment by samselikoff** [comment]
Ok, I see what's going on now.

First, you can see from the console that only the bands are being loaded, and the additional songs aren't being loaded on the initial request, nor are they being requested by your Ember app. So, there's two things you could do here. First, you can sideload the songs with the bands on the initial request. To do this, generate a `band` serializer:

```
ember g mirage-serializer band
```

and make it look something like this

```js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({

  include: ['songs']

});
```

This is saying, every time your Mirage mock server serializes a `band` model, include that band's related songs. This would get the songs to load on the initial request.

Alternatively, if you want to keep your models asynchronous, you need to provide a `links` hash with each model. That's how async works - Ember needs to know where to fetch the related models.

You could do this in your fixtures, something like this:

```js
export default [
  { id: 1, name: 'Pearl Jam', links: {songs: '/bands/1/songs'} },
  { id: 2, name: 'Led Zeppelin' links: {songs: '/bands/2/songs' }},
];
```

You could also do it in your serializer to save yourself from having to manage ids:

```js
// mirage/serializers/band.js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({

  serialize() {
    // This is how to call super, as Mirage borrows [Backbone's implementation of extend](http://backbonejs.org/#Model-extend)
    let json = ApplicationSerializer.prototype.serialize.apply(this, arguments);

    json.links = {
      songs: `/api/bands/${json.id}/songs`
    };

    return json;
  }

});

```

If you do this, you'll notice that Ember will make the second request once your template iterates through the band's songs. The request will fail, since that's a second route you'll need to mock in Mirage (i.e. it's a new endpoint that your actual server must implement). It might look something like this:

```js
// mirage/config.js
this.get('/bands/:id/songs', (schema, request) => {
  let id = request.params.id;
  let band = schema.band.find(id);

  return band.songs;
});
```

The last thing to be aware of is that your app is using Ember Data's RESTSerializer but your Mirage mock server is using ActiveModelSerializer. AMS is meant for an AMS-style backend, so you may run into some inconsistencies. If this is just for a demo app, I'd suggest going ahead and setting up your Ember app to use AMS. If there's going to be an actual server, you should write your mock server in the same format of the real server.

---

Remember that the point of Mirage is to mock your actual server, so when thinking about async vs sync models, how much to load up front etc., it all depends on the actual app you're building, and what the production server requirements will be.

Let me know if you need any more help!

**Comment by balinterdi** [comment]
Sorry for the delay, your exhaustive explanation helped me understand and fix this. It makes sense, so let me close this.

Thank you.

**Comment by ballPointPenguin** [comment]
This is very helpful. You guys are the best :hamster:

**Comment by balinterdi** [comment]
Hey Ben, see you at EmberConf?

**Comment by ballPointPenguin** [comment]
@balinterdi Yes!!!
