### ISSUE TITLE
PATCH?

### ISSUE THREAD

**Issue by ksnyde** [samselikoff/ember-cli-mirage#612]
I noticed that the verbs supported include `put` but not `patch`? Wondering how to navigate this on project which is using JSON-API where only PATCH is supported.

**Comment by zachfedor** [comment]
We're just trying to figure this out too. It seems [Pretender](https://github.com/pretenderjs/pretender) supports `PATCH`, so my hope is that this is just a lack of documentation.

However, our `this.patch` routes in Mirage don't seem to be working... So my hope might be unfounded.

**Comment by samselikoff** [comment]
Busy to look into this now but I thought I added this https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/server.js#L270... it's not working at all?

**Comment by zachfedor** [comment]
I was under the assumption that our `PUT` routes in `mirage/config.js` were recently updated to `PATCH` in order to match JSON:API spec. But I looked through the git history of our project and I was wrong: they were always `PATCH` routes. I posted here too soon.

Since our `PATCH` routes were working at some point, so this issue may be moot. I isolated the branch that introduced breaking changes but I'm still investigating. I'll report back as soon as I find anything.

I should also clarify what isn't working, in case someone else is having a similar issue or if anyone knows what might be wrong. Running version 0.2.0-beta.5, we are mixing fixtures and factories in our default scenario (i.e. mocking a product inventory with fixtures and creating users and orders with factories). Serving the app in dev we can see all of our mock data and create new users and orders through the app. The patch routes work for models created via the app, but not for the mock data created by the default scenario. We can change values on the front-end, call `.save()`, see the `update` hook running in Mirage, but the old data is never actually replaced with the new values.

**Comment by samselikoff** [comment]
Can you post your `config.js`?

**Comment by zachfedor** [comment]
I think we found the problem and it doesn't have to do with `PATCH` vs. `PUT` requests. We were updating a model's relationships without actually changing either model. I submitted a [PR](https://github.com/zachfedor/ember-cli-mirage/tree/bugfix/updating_relationships) with our fix. I don't want to hijack this issue, so I can create a new one or we can continue discussing things over at the PR. Whichever you'd prefer.

**Comment by samselikoff** [comment]
Let's move to new issue if you're still running into issues. 

I'll leave this open until we resolve @ksnyde's original problem.

**Comment by samselikoff** [comment]
@ksnyde I just tested out the shorthand

```js
this.patch('/authors/:id')
```

and my Ember app's PATCH request was handled successfully. Could I see some more info from your `mirage/config.js` file, and perhaps the Ember request that you're having trouble with?

**Comment by ksnyde** [comment]
@samselikoff I think we should close it then unless we keep it open for documentation purposes ... I just started using Fortune.js (and JSON-API) so I was just noticing the documentation was unclear on this support.

**Comment by samselikoff** [comment]
d9c32cdd841898a5b2204688e7549e02460ca9db closes
