### ISSUE TITLE
Upgrading from beta4: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application

### ISSUE THREAD

**Issue by promisedlandt** [samselikoff/ember-cli-mirage#621]
Upgrading from beta4 to beta5 or beta7 gives the following error in some tests:

`Promise rejected before TEST NAME: Assertion Failed: You cannot use the same root element (#ember-testing) multiple times in an Ember.Application`

While this shares part of the error message with #594, it looks to be a completely different issue.

Only integration tests are affected, but not all of them. In most of the affected tests, I don't even use mirage.

I have uploaded to the repository [here](https://github.com/promisedlandt/dominionsserver), with beta7 installed, so stuff will fail as soon as you run `ember test` (tested on 2 different machines myself).

**Comment by samselikoff** [comment]
For me, all the tests that didn't reference `server` passed. Make sure you run your tests with 

```
ember test --server
```

rather than `ember s` and visiting `/tests`.

For your failing tests that use `server.create`, you have some code like this:

```
pretender = server.create "dominions4-pretender"
@set("pretender", pretender)
```

`server.create` returns a _Mirage_ model, which is only intended to be used for your mocking layer (ie your server). You should not be passing Mirage models as params to your Ember components; Mirage knows nothing about your Ember app and it should stay that way.

If you absolutely must use `server.create` to leverage Mirage factories, than turn Mirage.Model's into POJOS via `#attrs`:

```
pretender = server.create "dominions4-pretender"
@set("pretender", pretender.attrs)
```

But, Mirage is not intended to be used this way, so you may run into bugs. `server.create` is intended to be used strictly to set up your mock server state.

**Comment by samselikoff** [comment]
Also, try running `server.shutdown()` in `afterEach` if you're manually starting Mirage.

**Comment by promisedlandt** [comment]
Thanks again for your help. Adding `server.shutdown()` didn't change anything.

> For me, all the tests that didn't reference server passed.

That's interesting to me. 
Do you mind sharing the versions of the software you used that could have an effect on this? I'm guessing `node`, `npm`, `ember-cli` could influence the result?  
Because I tested with a VM where I installed everything from scratch and got the error from the title.

> `server.create` returns a Mirage model, which is only intended to be used for your mocking layer

Right - but it didn't do that in beta.4 I think? So I'll need to change that in my upgrade, thanks.

> But, Mirage is not intended to be used this way, so you may run into bugs. server.create is intended to be used strictly to set up your mock server state.

What would be the Mirage way of unit testing components with models then? Explicitly setting the attributes in `server.create`, then building a POJO by hand and passing that to the component via `this.set`?

I don't mind rewriting my tests, this is a learning project anyway.

**Comment by samselikoff** [comment]
Right, `server.create` now returns `Mirage.Model` instead of a POJO, but even still, it should never have been used as instance data in your Ember app. Basically, the data from Mirage should live in Mirage-land, and only make it to Ember via an HTTP request. 

Mirage shouldn't be involved in unit testing components. Mirage models have nothing to do with Ember Data models - I know this is confusing, it's not your fault it's mine + the messaging. But Mirage.Model is completely separate and wholly distinct from Ember Data models. Mirage.Model is just used by Mirage to handle relationships in Mirage's in-memory db.

If you need an easy way to make Ember Data models for unit tests, you may want to check out Ember Data FactoryGuy. You can also make models right in the test by looking up the store.

**Comment by promisedlandt** [comment]
Got it, I'll try the store lookup, and if that doesn't work, it's FactoryGuys turn.

However, I still have the issue from the title with tests that don't use any Mirage features at all (and that work for you).
It makes me think the problem isn't really Mirage related, but downgrading to beta4 fixes it, so I'm stumped. This shouldn't happen when dependencies are specified in bower.json / package.json, right?

**Comment by samselikoff** [comment]
Correct... after upgrading try running `ember g ember-cli-mirage`, that will ensure the deps added by Mirage are upgraded. Sometimes it fixes things.

**Comment by promisedlandt** [comment]
Alright, if I comment out the non-passing test it works. Apparently the failing test didn't clean up after itself, causing the error message for all following tests.

Thanks for your time once again.

**Comment by samselikoff** [comment]
:+1: glad you figured it out, and sorry you ran into this!

**Comment by jcowley** [comment]
Running into this as well when enabling mirage in my test environment. I'm using v0.2.0-beta.9. 

The fact that a failing test causes the side effect of having other unrelated tests fail with "You cannot use the same root element (#ember-testing) multiple times in an Ember.Application" is a bug IMHO.

**Comment by jcowley** [comment]
Removing the shutdown seemed to fix it for me somehow:
```
afterEach() {
   window.server.shutdown();
}
```
But, honestly, these errors just seems to intermittently appear and disappear. I'm not sure this is related.

**Comment by samselikoff** [comment]
Did you have that call to `window.server.shutdown()` from before? Maybe it's because we added the [destroy-app helper](https://github.com/samselikoff/ember-cli-mirage/blob/ac7caea1255f4c808c66721129050e5b91860461/tests/helpers/destroy-app.js)? 

Should we add to the upgrade docs to remove all manual calls to `server.shutdown()` since this helper now exists?
