### ISSUE TITLE
hasMany + inverse without a belongsTo

### ISSUE THREAD

**Issue by blimmer** [samselikoff/ember-cli-mirage#628]
I've run into an issue, and am trying to figure out if it's a bug or not.

Using beta.7 + @ef4 's inverse foreign keys pr (https://github.com/samselikoff/ember-cli-mirage/pull/603), I have an issue with my hasMany's being removed from the attributes hash. Consider this situation:

```javascript
// app/models/event.js
export default DS.Model.extend({
  name: DS.attr('string'),
  primaryContacts: DS.hasMany('contact'),
  additionalContacts: DS.hasMany('contact'),
});

// app/models/contact.js
export default DS.Model.extend({
  name: DS.attr('string'),
});
```

So an event `hasMany` contacts split between primary and additional contacts. Given:

```javascript
// mirage/models/event.js
export default Model.extend({
  primaryContacts: hasMany('contact', { inverseOf: 'primaryContact' }),
  additionalContacts: hasMany('contact', { inverseOf: 'additionalContact' }),
});
```

It will strip primary/additional contacts from the payload. If I don't define them in the mirage model, it works. Is that intentional? Am I missing something here?

**Comment by blimmer** [comment]
I created a simple example [here](https://github.com/blimmer/ember-cli-example-app-for-github/commit/853f4b3407a6ebec542d965518c93b4d92807f2c). If you grab that app, fire it up and go to index, you'll see the issue.

![](https://i.imgur.com/0XW42Br.png)

Primary Contacts is defined in the mirage model as a `hasMany`, and additionalContacts is not, which is why they're showing up.

**Comment by samselikoff** [comment]
Ok, I got it working.

First, `inverseOf` needs to point to the key on the other side of relationship that points back to this model. So in this case, your models should look like this:

```js
// mirage/models/event.js
import { Model, hasMany } from 'ember-cli-mirage';

export default Model.extend({
  primaryContacts: hasMany('contact', { inverseOf: 'primaryEvent' }),

  // if you uncomment this, it will stop working
  additionalContacts: hasMany('contact', { inverseOf: 'additionalEvent' }),
});

// mirage/models/contact.js
import { Model, belongsTo } from 'ember-cli-mirage';

export default Model.extend({
  primaryEvent: belongsTo('event', { inverseOf: 'primaryContacts'} ),
  additionalEvent: belongsTo('event', { inverseOf: 'additionalContacts'} ),
});
```

You need to define the other side of the relationship here, because it's the belongsTo side that owns the foreign key. (Think about it at the database level).

Now, you want to create the data. You had something like this

```js
const primaries = server.createList('contact', 2);
const additional = server.createList('contact', 4);

server.create('event', {
  name: 'Event 1',
  primaryContactIds: primaries.map((c) => { return c.id; }),
  additionalContactIds: additional.map((c) => { return c.id; }),
});
```

but again it's best to think about this at the database level. Who owns the foreign keys? The belongsTo side. So when `server.create`ing, never pass in an `ids: []` array, since that will "confuse" the database + relationships. In this case, you want to point the contacts to the event, something like this:

```js
let event = server.create('event', { name: 'Event 1' });

// Primaries contacts
server.createList('contact', 2, { primaryEventId: event.id });
// Additional contacts
server.createList('contact', 4, { additionalEventId: event.id });
```

Now that the database is set up, you want to think about the serialization layer. It looks like you want GET /events to return events with the two types of `contact_ids` embedded. I think I'm so used to sideloading that there's currently no first-class API for just including ids. So in this case you'd want to do something like this in an EventSerializer:

```js
// serializers/event.js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({

  serialize(event, request) {
    let json = ApplicationSerializer.prototype.serialize.apply(this, arguments);

    json.additional_contact_ids = event.additionalContactIds;
    json.primary_contact_ids = event.primaryContactIds;

    return json;
  }

});
```

Now the app will work, and you'll see the various requests. But note that this is an n+1 thing, and your actual server shoudln't do this. You should either explicitly sideload

```js
// serializers/event.js
import ApplicationSerializer from './application';

export default ApplicationSerializer.extend({

  include: ['primaryContacts', 'additionalContacts']

});
```

which would sideload all additional and primary contacts on the first GET /events request, or use something like `links` so the server can respond with all of contact 1's additional contacts in a single response.

> NOTE: The above is actually not working, even though it should, so there's a bug. The `include` keyword is not using the property keys for the embedded_ids piece, so it won't work right now. But, the idea is correct, and I can get out a fix for this shortly. Let me know if that doesn't make sense.

**Comment by blimmer** [comment]
I just tried this out and I think this is how I should set it up. I found #636 and I think that fix would fully enable this. Thank you very much for your time in helping me with this!!
