### ISSUE TITLE
add ember-suave and fix any/all javascript linting errors

### ISSUE THREAD

**Issue by bantic** [samselikoff/ember-cli-mirage#657]
Mentioned by @samselikoff as a useful task that's good for new contributors that could be done to help improve the overall code cleanliness of mirage.

**Comment by lependu** [comment]
Hi, There are 13 failing test after installed ember-suave. I am working on it.

**Comment by lependu** [comment]
For the record, rebuilding the project from scratch brought back the failing tests. But I still don't have any idea why it passes in my local environment after a while.

Still some work to do, but there is some talking points:

- [ ]  Filtered out the the disallowEmptyBlocks rule due the fixtures/config/*.js files. As I see the other option is commenting out the empty blocks in those files.

- [ ] Filtered out requireSpread rule because I couldn't figure out how to pass 

> //tests/helpers/module-for-acceptance.js
> options.beforeEach.apply(this, arguments);

**Comment by samselikoff** [comment]
Awesome, thanks for the PR!

Is it possible to ignore certain rules within the files instead of omitting all linting from these problem files completely?

**Comment by lependu** [comment]
As far I know `// jscs:disable` disables entry file, `// jscs:disable ruleName` disables specific rule  in file.

**Comment by amyrlam** [comment]
Hi @lependu! Not working on it, you can implement...had never seen that before. 

Since we fixed all the JSCS errors I guess it would report nothing rn, but may be useful for future error debugging?

**Comment by samselikoff** [comment]
I think we can filter out the errors for the known issues (e.g. snake_case) but leave the rest

**Comment by lependu** [comment]
Ok, then I give it a try.

**Comment by lependu** [comment]
It seems adding filters through `.jscsrc` broke tests, so I removed them completely. Please see previous comment. The same is true of the 'errorFilter' implementation.
So, converted them into inline filters and added `/.jscsfilters` file with the list of them in case someone wants to review it.

Because @samselikoff added global `requireSpread` and `requireParenthesesAroundArrowParam` filters in #670 I applied those filters in the current fixes. My question is what we shall do with the fixes commited in #661 regarding those rules?

**Comment by acorncom** [comment]
@samselikoff Looks like the latest PR was merged, what additional items are you after here?
