### ISSUE TITLE
add jsdoc style inline documentation to methods

### ISSUE THREAD

**Issue by bantic** [samselikoff/ember-cli-mirage#658]
Mentioned by @samselikoff as a task that would be good for new contributors. Adding [JSDoc style](http://usejsdoc.org/howto-es2015-classes.html) comments for methods would help improve the overall quality of documentation.

**Comment by samselikoff** [comment]
Some more details:

[YUIDoc](http://yui.github.io/yuidoc/syntax/index.html) is a syntax for adding comments to code. You add a comment to an object, method or property in a structured way, and then later you can run a tool to parse the comments from your code. The parsed comments can be used for all sorts of things, like autogenerating a documentation site. This is how [Ember's API docs](http://emberjs.com/api/) are generated - the descriptions for each object and method actually come from the code. This is great, because that means they stay up to date.

Here's an example of a YUIDoc for the `Ember.Route#serialize` method: https://github.com/emberjs/ember.js/blob/master/packages/ember-routing/lib/system/route.js#L341-L347.

I'd love to get this into Mirage! We could eventually autogenerate the API docs from the code, which would be amazing.

A great place to start in Mirage would be the new `orm/Model` class.

- [Here's the class](https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/orm/model.js)
- And [here's the docs from the site](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.7/models/)
    - Note the methods in the "Class methods" section are on `schema.js`, so you can ignore those as a first pass.

The idea would be, basically copy the info from the docs, and write it as structured YUIDoc in the code, adding the important things like `@method`, `@param`, and so on, and marking methods `@private` or `@public`.

I would probably start with a single file and then PR it, and we can discuss from there.

**Comment by samselikoff** [comment]
For anyone else interested in jumping in, check [Liz's PR](https://github.com/samselikoff/ember-cli-mirage/pull/682) for a great example on a single class.

**Comment by lizzerdrix** [comment]
Trying to figure out which file to tackle next - any suggestions? I couldn't find any more that were quite as straightforward (in terms of their being similar enough to the docs that I could easily figure it out) as the ones I've already done. I can easily just pop in the basics (making note of the function name, params, and whether public/private) on any file, if that's helpful.

**Comment by samselikoff** [comment]
I think it is helpful, definitely. I'm wondering what the path for us to get to autogenerated API docs from the YUI comments would look like. I think ember-concurrency does this, and they even have Travis autobuild + deploy. If you want to, you could look into how they do that. Would be really great if we could ensure the API docs are always in sync with the code comments!

**Comment by lizzerdrix** [comment]
That would indeed be sweet - I will look into that over the next few weeks (will be easier after RailsConf 😛 ) and I'll get started adding some generic comments to the other files.

**Comment by lizzerdrix** [comment]
Started messing around with [ember-cli-yuidoc](https://github.com/cibernox/ember-cli-yuidoc) (which is how the Ember API docs are generated). I was able to generate some HTML pages, but still trying to figure out exactly how to parlay these into an actual documentation site. Sadly, the documentation for the addon is not super helpful, but I'll keep futzing with it and see what I can get!

**Comment by alecho** [comment]
@samselikoff You're just looking for people to start adding the docblocks now, not actually work on generating anything from them, yet? If so I'm interested in this one. I saw Waffle.io recently added support for multiple assignees for a ticket. With that in mind I'm interested in this one.

**Comment by samselikoff** [comment]
@alecho yes sir. That would be wonderful. Why don't I make a new ticket for each undocumented class, and we can track it that way

**Comment by samselikoff** [comment]
Add one to Ready and the rest to the top of Chores: https://waffle.io/samselikoff/ember-cli-mirage

Closing this issue for now since we've kicked off the process. Thanks everyone for getting this started!
