### ISSUE TITLE
Mirage makes an api request for a model already loaded in the store

### ISSUE THREAD

**Issue by thedrew12** [samselikoff/ember-cli-mirage#701]
I'm using mirage in development and I have one route that loads all of the models. When I change route through `link-to 'route' id` I pass in the id for the specific model I'm routing to. Ember finds the record in the store by a `findRecord` and returns the data. If I don't have mirage endpoint setup `this.get('/endpoint/:id')` it throws a mirage error, but the data still gets loaded. If I put the mirage enpoint in when it hits this dynamic route it finds the record in the store and also mirage sends back an api response with the same data. Now I have two instances of everything in the route.

I think the expected behavior when I using mirage is it should not make an api request if I have the data already loaded in the store, but it makes a request every time i change routes. Any help would be appreciated.

**Comment by samselikoff** [comment]
Are you using Ember Data? I believe this is [#shouldBackgroundReloadRecord](http://emberjs.com/api/data/classes/DS.Adapter.html#method_shouldBackgroundReloadRecord) in action. I think the default for `findRecord` is to resolve immediately with any record in the store, and in the background hit the network for updated data.

Remember that Mirage knows nothing about your Ember app. Since your Ember app is making the additional request, that would still be the behavior even if you were hooked up to a real server. Does that make sense?

Lastly if you're using Ember Data an additional network request typically isn't a problem, since Ember Data's store is an identity map. The new data will be pushed into the store but you wouldn't have a duplicate, you would just get any updates (if there were any).

Let me know if that helps!

**Comment by thedrew12** [comment]
Thanks for the feedback @samselikoff.
