### ISSUE TITLE
Add pagination support to JsonApiSerializer

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#710]

**Comment by Azdaroth** [comment]
Hey Sam, have you had some new ideas on pagination?

That's something I deal occasionally with and would be really nice to have something working out of box. Actually, I even needed it for an addon I released last week for dedicated pagination for JSONAPI backend and that's how I handled it in the dummy app: serializer (https://github.com/BookingSync/ember-cli-jsonapi-pagination/blob/master/tests/dummy/mirage/serializers/rental.js) + customized route handler (https://github.com/BookingSync/ember-cli-jsonapi-pagination/blob/master/tests/dummy/mirage/config.js). 

JSONAPI doesn't enforce any particular strategy for pagination, so not really sure if all strategies mentioned in the docs should be supported (page-based, offset-based and cursor-based) or only 1 or 2 of them, it seems (arguably) the page-based is the most commonly used one. What were your plans here?

Wondering if it's something that should be handled on serializer-only level,  seems more natural to have it on route handler level which is closer to what actually happens when interacting with real backend.

Thoughts?

**Comment by samselikoff** [comment]
I haven't thought much about this one yet. I believe when I opened it I thought there was only one way to do pagination in json:api, so I thought we should add it to the serializer.

Since there's not, it might make sense to try to tackle the general "meta" problem, that is, how to get metadata to the serializer layer. Then, the serializer can decide where to put it.

**Comment by Azdaroth** [comment]
How about handling pagination logic in route handlers? Actually the same thing applies to ordering and filtering as well. In real world scenario all these things happen server-side, so it might make sense to reflect the same thing in route handlers.

For the meta data, this could probably come from route handlers, just like it comes from the backend  and then maybe passed as the 3rd argument to `serialize` method and the serializer would do the rest?

**Comment by samselikoff** [comment]
Yah - would you like to propose an API? We need to think of a way to get the meta from the route handler to the serializer. Problem is, you need to be able to respond with a POJO or POJA from route handlers and have that go through. 

We might need to extend Mirage.Response, and maybe you return an instance of that that has the metadata attached to it.

**Comment by Azdaroth** [comment]
Yeah, I could give it a try and see what works best in this case. If I have enough time I'll play with it this weekend.

**Comment by hbrysiewicz** [comment]
Feature requests are being moved to Canny. 
[View this feature request on Canny](https://ember-cli-mirage.canny.io/feature-requests/p/pagination-support-in-jsonapiserializer)

**Comment by mansur-gabidullin** [comment]
Pagination with sorting example:

`
import get from 'lodash/get';

function compareBy (key, ascending) {
    let reverse = ascending ? 1 : -1;

    return (a, b) => {
        const aV = get(a, key);
        const bV = get(b, key);

        if (typeof aV === 'string') {
            return aV.localeCompare(bV) * reverse;
        }

        if (aV < bV) return -1 * reverse;
        if (aV > bV) return 1 * reverse;

        return 0;
    };
}

const ApplicationSerializer = RestSerializer.extend({
    root: false,
    embed: true,
    keyForAttribute: (name) => {
        return name;
    },
    serialize (resource, request) {
        const {queryParams} = request;

        let json = {
            data: RestSerializer.prototype.serialize.call(this, resource, request)
        };

        if (request.method === 'GET' && Array.isArray(json.data)) {

            if (queryParams.order_by) {
                const {
                    order_by,
                    order_dir = 'asc'
                } = queryParams;

                json = {
                    ...json,
                    data: json.data.sort(compareBy(order_by, order_dir === 'asc'))
                };
            }

            if (queryParams.size) {
                const from = Number(queryParams.from || 0);
                const size = Number(queryParams.size || 0);
                const page = json.data.slice(from, from + size);

                json = {
                    ...json,
                    recordsTotal: json.data.length,
                    recordsCount: page.length,
                    data: page
                };
            }
        }

        return json;
    }
});
`

**Comment by cah-briangantzler** [comment]
Mirage has since been extracted to https://github.com/miragejs/miragejs. This addon now only adds some helpers for ember.  It might be helpful if this answer was also posted on their site to aid others more than just the Ember community.
