### ISSUE TITLE
Camel-case not working following Upgrading documentation

### ISSUE THREAD

**Issue by typeoneerror** [samselikoff/ember-cli-mirage#752]
I'm getting started with 0.2 beta, and I've found that even thought the upgrade docs say everything should be camelCased ("All JavaScript properties are camelCased."), that I only see data in my app if I stick with `underscore_names`. I am using ActiveModelSerializer so my app is expecting data in underscore format, so I'm unsure if the serializer layer is working correctly and I should be sticking with underscore or are "all Javascript properties camelCased" for JSON API only?

**Comment by samselikoff** [comment]
The Serializer should normalize incoming data so by the time it makes it into Mirage's database, it's camelCased.

Did you see [the serializer guids](http://www.ember-cli-mirage.com/docs/v0.2.0-beta.9/serializers/), and have you specified your application serializer to be AMS?

**Comment by samselikoff** [comment]
Note that if you're writing custom route handlers, the data in `request.requestBody` will be whatever format your API is in. You can use `this.normalizedRequestAttrs()` from within the handler to get the normalized version of the attrs.

**Comment by typeoneerror** [comment]
Thanks for your feedback, @samselikoff. I did read the latest guide, but feel like I must be missing something. Here's my setup:

```js
// mirage/serializers/application.js
import { ActiveModelSerializer } from 'ember-cli-mirage';
export default ActiveModelSerializer.extend({
});

// mirage/scenarios/default.js
store.create('user', { email: 'ben@weareokioki.com', firstName: 'Ben', lastName: 'Borowski', roles: ['admin'] });

// mirage/models/user.js
import { Model } from 'ember-cli-mirage';
export default Model.extend({
});

// mirage/factories/user.js
import Mirage, {faker} from 'ember-cli-mirage';
export default Mirage.Factory.extend({
  email: function(i) { return 'user' + i + '@test.com'; },
  firstName: faker.name.firstName,
  lastName: faker.name.lastName
});

// mirage/config.js
this.get('/users/current', ({ users }, request) => {
  //console.log(request.requestBody);
  //console.log(users.first());
  return { user: users.first() }
});
```

With `{{currentUser.firstName}}` in the app, nothing shows up. However, if I change `firstName` to `first_name` in the default scenario and the factory, `{{currentUser.firstName}}` shows the factory-generated name. Could I not be using the application serializer correctly? Do I need to call `this.normalizedRequestAttrs()` as you mentioned in the "get" since that is a "custom route handler"?

**Comment by samselikoff** [comment]
Ah. So, it is a custom route handler, but no you don't, since you're not doing anything with the attrs from the request (i.e., this is just a GET).

What you want to do is just do this:

```js
this.get('/users/current', ({ users }, request) => {
  return users.first();
});
```

By returning just a user Model, you're telling this route handler to opt-in to Mirage's serializer layer. The Serializer layer is responsible for the format of your response, including putting the root `user` in the JSON payload, so you don't have to.

Next time you run into an issue, first check the console in your Ember app, to see if Mirage is responding the way you expect. If you're in a test, console logging is disabled by default. To enable it, write `server.logging = true` at the top of your test. Finally, for one last debugging trick, after your Ember app has made the request, check the Ember inspect and look in the Data tab to see if the data has been loaded as you expect.

Lastly, you have made a custom route handler here, to respond with the first user in your Mirage database. In fact if you just create a user with the `id` of `current`, you can use the shorthand.

```js
// mirage/scenarios/default.js
server.create('user', { id: 'current', email: ... })

// mirage/config.js
this.get('/users/:id');
```

and that should be it!

**Comment by typeoneerror** [comment]
@samselikoff brilliant, Sam, thank you! can you DM me an email address on Twitter (@typeoneerror) so I can paypal you a tip for your time?

**Comment by samselikoff** [comment]
No need, thanks for the love. Best of luck!
