### ISSUE TITLE
Bug with reflexive relationships

### ISSUE THREAD

**Issue by samselikoff** [samselikoff/ember-cli-mirage#755]

**Comment by cibernox** [comment]
Just my 5 cents that I came across this same problem when I had an User with a hasMany relationships for users.

Example: https://github.com/cibernox/ember-power-select/blob/39112c406d297a68a05a969b7a6c5289b695ff57/tests/dummy/mirage/models/user.js

That was enough to generate a stack overflow for a recursive call when the serializer was trying to serialize other users.

Since in this addon the dataset was just an example, I just decided to create a different model, but hopefully this helps reproduce the issue.

**Comment by marxsk** [comment]
@samselikoff 

Do you have a test case that you wish to support? I thought that it is not working but I have created a minimal example and it looks like it works. My models are:

```javascript
export default DS.Model.extend({
  resources: DS.hasMany('resource'),
});

export default DS.Model.extend({
  name: DS.attr('string'),
  resources: DS.hasMany('resource', {
    inverse: null,
    async: true,
  }),
});
```
with mirage-models containing just hasMany('resource') and serializer with include: ['resource']

**Comment by samselikoff** [comment]
Hm, nice to see that. I wonder if you try to get the belongsTo side, though? e.g. if you had a

```js
parent: DS.belongsTo('resource')
```

**Comment by marxsk** [comment]
ok, I have prepared a repository, so you can check it too. Take a look at https://github.com/marxsk/mirage-reflexive

* hasMany/belongsTo - works as expected

but there is a limitation (as seen in mirage/scenarios/default.js), you cannot use createRecord because it lead to 'maximum call stack exceed'. It might be easy to fix but I did not attempt to do it as workaround is really simple. It is enough to use createXYZ (XYZ = model) on a created record.

**Comment by samselikoff** [comment]
right. Ok thanks for the repo. I am hashing out a plan to attack the remaining ORM issues (reflexive, manyToMany, polymorphic) soon, so that should address this.

**Comment by mellatone** [comment]
@samselikoff ping me when you have that plan hashed out so I can contribute.

**Comment by samselikoff** [comment]
Thanks, still working through bit of a backlog of issues, then going to wrap up the serializer PR. Will be soon.

**Comment by Leooo** [comment]
all I can say right now is that, yes, there is a problem with reflexive relationships.

`````
// answer.js
questions: hasMany('question', {inverse: 'parentAnswer'}),
parentQuestion: belongsTo('question', {inverse: 'answers'}),
`````

`````
// question.js
parentAnswer: belongsTo('answer', {inverse: 'questions'}),
answers: hasMany('answer', {inverse: 'parentQuestion'}),
`````

**Comment by Leooo** [comment]
Same issue why Ember doesn't track dirty relationships, and why it's hard to build offline adapters (localStorage etc.)

**Comment by cibernox** [comment]
> Same issue why Ember doesn't track dirty relationships, and why it's hard to build offline adapters (localStorage etc.)

@Leooo Are you taking about mirage or about Ember-Data?

**Comment by Leooo** [comment]
@cibernox I meant in general, hard to know when to save dirty relationships etc., whether it is in Ember-data or Mirage models (which are getting closer to ED models actually).

**Comment by samselikoff** [comment]
Closing this, as we just need proper support in ORM (in progress).
