### ISSUE TITLE
addon installs .js files in a coffeescript app

### ISSUE THREAD

**Issue by justin-hackin** [samselikoff/ember-cli-mirage#78]
Thus installing this addon to a coffeescript project causes parsing errors in a CLI project

**Comment by samselikoff** [comment]
I don't write coffeescript, do you know what other addons do?

**Comment by clekstro** [comment]
@samselikoff see the comments [here](https://github.com/switchfly/ember-cli-mocha/issues/12).

**Comment by blimmer** [comment]
@justin-hackin the trick would be to create your own blueprints and publish an addon (like ember-cli-mirage-coffeescript). 

For an example, you could have a look at [ember-cli-mocha-coffeescript](https://github.com/Ibotta/ember-cli-mocha-coffeescript), which we used during our transition away from :coffee: .

Since ES2015 is the standard for the ember community, I'm going to close this issue.
