### ISSUE TITLE
fixture responses always wrap store fetches in an object

### ISSUE THREAD

**Issue by justin-hackin** [samselikoff/ember-cli-mirage#79]
When I set up a get for a list of models, instead of getting a list, I get 
{things:[list of things]} instead of just the list of things.

That makes me rewrite the get method as such
@.get('/things', (db)->
    return db.things
  )

It would be nice if you could turn off this wrapping of responses for all requests

**Comment by justin-hackin** [comment]
Maybe there is a reason for this wrapping though ... ?  Like to help with sideloading ?

**Comment by samselikoff** [comment]
Yep serializers (#2) will take care of this, the reason it's wrapped is because this lib was originally designed to work with a particular API format.

Serializers will take care of things like whether to include key in root, whether to sideload related models, which attrs to include, etc.

Right now factory associations are priority 1, but serializers will be coming soon. Perhaps I could add them in with just the `includeRoot` option for now.

**Comment by mattlindsey** [comment]
+1 to 'includeRoot' option.  I'm pretty new to this stuff and need help.
  
My problem is that I'm using JSTree (www.jstree.org) which requires no root_key when loaded.
So how do I write this to remove the root_key?

  this.get('/report_rollups', function(db) {
    return db.rollups;
  });

**Comment by samselikoff** [comment]
What you're written won't return root, since you're just returning the array

**Comment by dwickern** [comment]
:+1: an `includeRoot` would be really nice

**Comment by samselikoff** [comment]
In 0.2.x, you can set `root` to false in the serializer layer http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#root
