### ISSUE TITLE
Passthrough pre-flight CORS requests are overriding access control headers

### ISSUE THREAD

**Issue by billdami** [samselikoff/ember-cli-mirage#806]
When I have ember-cli-mirage enabled, passthrough'ed CORS requests (for example, to my API server's /oauth/token endpoint) are having their pre-flight request's Access Control header values being set by mirage/pretender to values which are too limiting and as a result the server denies the request. For example, for this specific request, when it goes through the passthrough it adds the following headers:

```
Access-Control-Request-Headers:accept, content-type
Access-Control-Request-Method:POST
```

Whereas, when mirage is not enabled, these headers don't get set at all, which allows the server to respond with the values it accepts, i.e. for Access-Control-Request-Headers: "x-requested-with, Authorization, Content-Type", and for Access-Control-Allow-Methods: "POST, PUT, GET, OPTIONS, DELETE".

I tried modifying the mutating the headers to remove these headers in my mirage/config.js function, like this:

```javascript
this.pretender.prepareHeaders = function(headers) {
        delete headers['Access-Control-Request-Headers'];
        delete headers['Access-Control-Request-Method']
        return headers;
 };
```

But that doesn't seem to have any effect on the preflight requests, they still are setting those header values.

**Comment by billdami** [comment]
Can be disregarded, my server was just not configured to support OPTIONS requests for that specific endpoint.  :-)

**Comment by xamoom-pali** [comment]
There would still be a case to reopen this thread. We are using [Pushwoosh](https://www.pushwoosh.com/) service to send push notifications, but a POST request fails because a pre-flight OPTIONS request is sent prior to it. Since Pushwoosh is not our backend and it expects the request having a certain structure, the OPTIONS request ends with **400 Bad request data**. 

If I turn off ember-cli-mirage:

`ENV['ember-cli-mirage'] = {
      enabled: true
    };`

in the `config/environment.js` file, there is no OPTIONS request preceding the POST request and everything works as expected.

**Comment by ohcibi** [comment]
I ran into the same when trying to integrate Sentry. With ember-cli-mirage disabled there is no `OPTIONS` request. I think this issue should be re-opened
