### ISSUE TITLE
Enable per test?

### ISSUE THREAD

**Issue by sohara** [samselikoff/ember-cli-mirage#825]
We have a fairly large number of acceptance tests and we'd like to attempt to migrate from vanilla Pretender and fixtures to Mirage iteratively (one test at a time). Is this feasible?

**Comment by samselikoff** [comment]
I think the best bet here would be to

1. Install Mirage
2. Add `server.shutdown()` to the `beforeEach` hook of your `moduleForAcceptance` helper, so that in all your existing tests Mirage isn't running (it runs by default).
3. [Manually start Mirage](http://www.ember-cli-mirage.com/docs/v0.2.x/manually-starting-mirage/) in the tests where you want the server to run.

Happy to answer questions as you try this out!

**Comment by sohara** [comment]
Thanks very much @samselikoff! I will give that a try.
