### ISSUE TITLE
Base serializer doesn't support only sending one document

### ISSUE THREAD

**Issue by fivetanley** [samselikoff/ember-cli-mirage#833]
Given a serializer of:

``` javascript
export default Serializer.extend({
  root: false,
  embed: false
  include: []
});
```

Throws an error with a message of: `'You cannot have a serializer that sideloads (embed: false) and disables the root (root: false).'`

It seems like you shouldn't get this warning if you aren't actually sideloading/embedding any relationships.

**Comment by samselikoff** [comment]
Hm what's the expected response? Something like

```
GET /contacts/1

{
  id: 1,
  name: 'Stanley'
}
```

? If you _were_ to include a relationship, where would it go? It'd need to be embedded right? I think here you just want to 

```js
export default Serializer.extend({
  root: false,
  embed: false
  include: []
});
```

**Comment by fivetanley** [comment]
@samselikoff That's correct. In this scenario I *don't want to include any sideloaded relationships at all.* However, that configuration still results in an assertion error being thrown.

**Comment by fivetanley** [comment]
I'd be happy to submit a pull request.

**Comment by samselikoff** [comment]
Hm I think it's still fine... `embed` only affects what happens _when_ relationships are included. It shouldn't affect the response if there aren't any included resources. Did you try `root: false` and `embed: true`?

The reason the check (and error) exists is, if you ever _did_ include related resources, it would be logically impossible (since the primary resource has no root and thus there's no way to differentiate between the primary resource and the included resources).

**Comment by acorncom** [comment]
@fivetanley Any additional thoughts here or should we close?

**Comment by samselikoff** [comment]
Going to close this for now, happy to reopen and discuss. The idea behind the config warning is, in the event someone eventually includes related resources, the two options together aren't compatible. In that sense it's a misconfiguration.
