### ISSUE TITLE
Attempted to handle event `notFound` on  while in state root.deleted.saved

### ISSUE THREAD

**Issue by ImmortalDragonm** [samselikoff/ember-cli-mirage#853]
When i try to destroyRecord i get an error:

```Error: Attempted to handle event 'notFound' on <portal10@model:client::ember594:5> while in state root.deleted.saved.```

my code:

```
this.get('store').findRecord('client', 5).then((record) => {
      console.log("fulfilled");
      console.log(record.get('name'));
      record.destroyRecord();
    }, (error) => {
      console.log("rejected");
      console.log(error);
    })
```

mirage/config.js:

```
  this.get('/clients');
  this.get('/clients/:id');
  this.del('/clients/:id');
```

console output:
```

client-list.js:14 fulfilled
client-list.js:15 Domenic Jones
server.js:66 Successful request: DELETE /clients/5
server.js:77 Object {}
ember.debug.js:19754 Error: Attempted to handle event `notFound` on <portal10@model:client::ember531:5> while in state root.deleted.saved. 
    at new Error (native)
    at Error.EmberError (http://localhost:4200/assets/vendor.js:29816:21)
    at InternalModel._unhandledEvent (http://localhost:4200/assets/vendor.js:128090:13)
    at InternalModel.send (http://localhost:4200/assets/vendor.js:127968:14)
    at InternalModel.notFound (http://localhost:4200/assets/vendor.js:127872:12)
    at http://localhost:4200/assets/vendor.js:135821:21
    at tryCatch (http://localhost:4200/assets/vendor.js:62277:14)
    at invokeCallback (http://localhost:4200/assets/vendor.js:62292:15)
    at publish (http://localhost:4200/assets/vendor.js:62260:9)
    at publishRejection (http://localhost:4200/assets/vendor.js:62195:5)defaultDispatch @ ember.debug.js:19754dispatchError @ ember.debug.js:19737onerrorDefault @ ember.debug.js:33133trigger @ ember.debug.js:52820(anonymous function) @ ember.debug.js:53814invoke @ ember.debug.js:990flush @ ember.debug.js:1054flush @ ember.debug.js:862end @ ember.debug.js:176run @ ember.debug.js:298join @ ember.debug.js:318run.join @ ember.debug.js:24341hash.error @ rest.js:935fire @ jquery.js:3187fireWith @ jquery.js:3317done @ jquery.js:8759(anonymous function) @ jquery.js:9123(anonymous function) @ fake_xml_http_request.js:137dispatchEvent @ fake_xml_http_request.js:181_readyStateChange @ fake_xml_http_request.js:381_setResponseBody @ fake_xml_http_request.js:445respond @ fake_xml_http_request.js:466(anonymous function) @ pretender.js:335resolve @ pretender.js:372(anonymous function) @ pretender.js:363
server.js:66 Successful request: GET /clients/5
server.js:77 Object {}
```

**Comment by samselikoff** [comment]
Looks like your ember app is trying to GET `/clients/5` after you've deleted it.

The error message about state bing `root.deleted.saved` might be because you're not `return`ing `record.destroyRecord` from your action, so your app makes the GET before waiting for the DELETE to finish.

**Comment by samselikoff** [comment]
Let me know if that clears things up; if not, could you post some more code surrounding your method?

Happy to reopen if you need more help!

**Comment by ImmortalDragonm** [comment]
ember 2.7.2

All my code:

```
ember new destroy
cd destroy/
ember install ember-cli-mirage
ember g mirage-model product
ember g mirage-factory product
ember g resource products
ember g component product-item
ember server
```

app/templates/products.hbs:
```
<button {{action 'destroyItem'}}>destroy</button>
<ul>
  {{#each model as |product|}}
      {{product-item product=product}}
  {{/each}}
</ul>
```
app/routes/products.js:
```
import Ember from 'ember';

export default Ember.Route.extend({
  model() {
    return this.store.findAll('product');
  },
  actions: {
    destroyItem() {
      this.store.findRecord('product', 5).then( function(record){
        record.destroyRecord();
      })
    }
  }
});

```
app/models/product.js
```
import DS from 'ember-data';

export default DS.Model.extend({
  name: DS.attr('string')
});
```
mirage/factories/product.js:
```
import { Factory } from 'ember-cli-mirage';

export default Factory.extend({
  name(i) {return `product ${i}`;}
});
```
mirage/config.js:
```
export default function() {

  this.get('/products');
  this.get('/products/:id');
  this.del('/products/:id');
}
```
mirage/scenarios/default.js:
```
export default function(server) {
  server.createList('product', 10);
}
```
app/templates/components/product-item.hbs:
```
{{product.name}}
```
app/components/product-item.js:
```
import Ember from 'ember';

export default Ember.Component.extend({
  tagName: 'li'
});
```
app/router.js:
```
import Ember from 'ember';
import config from './config/environment';

const Router = Ember.Router.extend({
  location: config.locationType,
  rootURL: config.rootURL
});

Router.map(function() {
  this.route('products');
});

export default Router;
```

**Comment by samselikoff** [comment]
Are you meaning to call `this.store.findRecord('product', 5)` with the `id` 5 every time, or do you mean to pass the `id` in from the template? Typically you don't call `findRecord` just to `destroy`  since you already have that model loaded in the client. Can you show me the UI you're trying to build?

**Comment by ImmortalDragonm** [comment]
id 5 - it's for test only. it will get from template - sure. It doesn't matter how to get this number.

all files in my previous comment (it's a whole application to check this error)
in all tutorial:
```

      this.store.findRecord('product', 5).then( function(record){
        record.destroyRecord();
      })
```

as i test - it's not mirage problem. i created backend api in rails, and the same error.
why Ember get record after destroy?
Is it a bug in Ember?
I'm going to write bug report to ember team. Or i don't understand something?

**Comment by samselikoff** [comment]
I figured it out.

The way `findRecord` works is, if the model is loaded locally, `findRecord` returns the record synchronously and executes the `.then` callback immediately. In the background, Ember Data issues another network fetch to refresh the model.

The problem here is, the callback is executed (so the record is moved to the `deleted` state), but in the background Ember Data is essentially calling `model.reload()`. So you get into a weird state.

So you have a few options:

 1.  call `destroyRecord()` on the local model without calling `findRecord` (which you should do - no need to go back to the network just to issue a DELETE request)
 2. pass `{ reload: true }` option to `store.findRecord` so the code actually waits for the server to respond before calling `destroyRecord`
 3. change your Adapters settings to not do a background reload

Here's a fiddle showing `{ reload: true }` working, but you can also see the commented line works as well.

https://ember-twiddle.com/8217fec2b6e570bb8a4b61c1cafc216a?fileTreeShown=false&openFiles=routes.application.js%2C

**Comment by ImmortalDragonm** [comment]
All you options is a hack and workaround. It works. true. But:
for example i have paginations. User input line number and delete it. It can by on current page( and i need to use peekRecord), or on another page (and i need to user findRecord). Like this:
```
      var record = this.store.peekRecord('product', 5);
      if (record !== null){
        record.destroyRecord();
      } else {
        this.store.findRecord('product', 5).then(function(record){
          record.destroyRecord();
        })
      }
```
all the time i want to delete record.
this must be in ember guide.

**Comment by samselikoff** [comment]
Can you describe the UI in your app that allows users to delete a product that you haven't yet fetched? E.g. deleting product 5 when it's not rendered on screen?

I think this is not a standard use case (store.finding a model just to delete it) because normally you'd already have found it, rendered it on your app, then your user would click "delete" next to it (in which case you'd use store.peekRecord).

**Comment by stephanebruckert** [comment]
Same thing here, and following samselikoff advice, replaced:

    self.get('store').find('calendar-token', 1).then(function(r) {
        r.destroyRecord()
    })

by

    self.get('model.calendarToken').destroyRecord()

👍
