### ISSUE TITLE
Creating an empty object rejected as invalid JSON-API payload (type, but no attrs/rels)

### ISSUE THREAD

**Issue by nruth** [samselikoff/ember-cli-mirage#885]
I think there's a bug with creating empty objects. We currently have some code that does this, then creates other objects associated to it using the ID given back by the API.

`this.get('store').createRecord('something', {})` gives me

`ember.debug.js:19746 Mirage: Error: You're using a shorthand or #normalizedRequestAttrs, but your serializer's normalize function did not return a valid JSON:API document.` 

https://github.com/samselikoff/ember-cli-mirage/blob/master/addon/route-handlers/base.js#L45
is asserting json.data.attributes or relationship must be present, but json-api says only type is necessary for post/create requests. http://jsonapi.org/format/#crud-creating

Ember Data is sending it to faker as something like `requestBody: "{"data":{"type":"somethings"}}"` (found by dropping a `debugger` into the library code in node_modules).

I've been getting this on 0.2.1 and master.

Changing the assert to `json.data && (json.data.type || json.data.attributes || json.data.relationships)` fixes our app, but seems like a bad solution. It should probably check if it's a post/create or other kind of request?

**Comment by acorncom** [comment]
@nruth Would it be possible to get a failing test case for this?  Sam's been getting swamped, so trying to figure out how to have us all help him help us ;-)

**Comment by samselikoff** [comment]
I agree with you - I think we need to just change that check to match for `json.data && json.data.type`, based on what you've found in the spec.

Would you PR this?

**Comment by nruth** [comment]
Yes I will try to add tests and make the change, but need to clear another deadline first. Please poke me if I haven't submitted something by mid November.

I think `{ data: { type: '' }}` is only valid if it's a create action, the others need more, but will double-check when I get back to it.

**Comment by samselikoff** [comment]
Looking for someone to take this one on.

**Comment by alisdair** [comment]
If I'm reading the spec properly, `{"data":null}` would be a valid document. This is explicitly recommended in [the section about clearing a one-to-one relationship](http://jsonapi.org/format/#crud-updating-to-one-relationships):

> And the following request clears the author of the same article:
> 
>     PATCH /articles/1/relationships/author HTTP/1.1
>     Content-Type: application/vnd.api+json
>     Accept: application/vnd.api+json
>    
>     {
>       "data": null
>     }

And in [the top-level document description](http://jsonapi.org/format/#document-top-level):

> A document **MUST** contain at least one of the following top-level members:
> - `data`: the document’s “primary data”
>
> …
> 
> Primary data **MUST** be either:
> - a single resource object, a single resource identifier object, or `null`, for requests that target single resources

I'm not sure what the correct behaviour of `normalizedRequestAttrs` in this case would be. Returning `null`, I guess? Any thoughts?

**Comment by samselikoff** [comment]
@alisdair Looks like you're right. Seems like a less-used feature of the spec (I think people usually clear relationships by patching the owning resource with a `relationships: { model: data: null` payload rather than patching the relationship directly).

For now I'm closing as we addressed the original point, and we can always reopen/update the assertion if folks run into the `data: null` case!

**Comment by jelhan** [comment]
Just some thoughts for anybody coming here later:

> If I'm reading the spec properly, {"data":null} would be a valid document. This is explicitly recommended in the section about clearing a one-to-one relationship:
> [...]
> I'm not sure what the correct behaviour of normalizedRequestAttrs in this case would be.

`normalizedRequestAttrs` is not supporting [resource identifier objects](http://jsonapi.org/format/#document-resource-identifier-objects) at all. Resource identifier objects does not have any attributes. So that's fine IMO.

Who ever implements updating relationships using relationships links should not use that function. Resource helper does not register routes for relationship links. Ember-data does not use them to update relationships. I thinks that's basically the reason why not that many people use them in ember apps.
