### ISSUE TITLE
RestSerializer does not include "hasMany" relationship ids

### ISSUE THREAD

**Issue by H1D** [samselikoff/ember-cli-mirage#912]
It seems like RestSerializer does not serialize ids for hasMany realtionship.

Here made an example based on your boilerplate (just added `pet` models which is one-to-many for `user`) – https://ember-twiddle.com/259b0c0ee941777449274344834416ff/e4a8999888a9ee03646d4a4c4d8a402c6e0a0f63?openFiles=mirage.factories.user.js%2C

Totally same example but with default serializer works fine though https://ember-twiddle.com/259b0c0ee941777449274344834416ff

**Comment by samselikoff** [comment]
We added `serializeIds` in 0.2.2, I just added it to the docs [here](http://www.ember-cli-mirage.com/docs/v0.2.x/serializers/#serializeids). You should be able to set it to `always` and get all the ids every time.

All ids are serialized in the JSON:API serializer because that's how the spec defines the behavior.

Let me know if you have any more questions!
